#!/usr/bin/env python

from tests.test_downloadable import test_script_files_download, test_add_already_tracked_regimen
from tests.test_stage_name_in_params import test_stage_name_in_params

test_script_files_download()
test_add_already_tracked_regimen()
test_stage_name_in_params()
