_launcher_script: &launcher_script
    https://raw.githubusercontent.com/AllenNeuralDynamics/openscope-community-predictive-processing/4d0767e3da7d2c03c2d0ab805a4a8e7248c77323/code/experiment-launcher/bonsai_experiment_launcher.py
            
_launcher_script_md5: &launcher_script_md5
    29f37c4670ba9a32357036303e20d22a

_bonsai_launcher_parameters: &bonsai_launcher_parameters
    repository_url: https://github.com/AllenNeuralDynamics/ophys-passive-visual-stim.git
    repository_commit_hash: deac52d4f01c243ba789a424a31e3b1e219dd12e
    local_repository_path: C:/BonsaiDataSCBC
    bonsai_path: src/RandomNaturalMovies_Harpless.bonsai
    bonsai_exe_path: bonsai/Bonsai.exe
    bonsai_setup_script: bonsai/setup.cmd
    stimulus_table_duration: 00:01:00
    stimulus_table_path: ParameterFiles/pilot_stim_trials.csv
    Photodiode_ExtentX: 8
    Photodiode_ExtentY: 8
    Photodiode_LocationX: 59
    Photodiode_LocationY: -28

### mtrain definitions
name: SCBC_DiverseVisStim_v4

transitions:

  - trigger: progress
    source: DAY_6
    dest: DAY_7
    conditions: one_complete

  - trigger: progress
    source: DAY_7
    dest: DAY_8
    conditions: one_complete

  - trigger: progress
    source: DAY_8
    dest: DAY_9
    conditions: one_complete

  - trigger: progress
    source: DAY_9
    dest: DAY_10
    conditions: one_complete

  - trigger: manual
    source: DAY_10
    dest: TRAIN_FULL_DAY1_5

  - trigger: manual
    source: TRAIN_FULL_DAY1_5
    dest: TEST_CLUSTER

stages:
    DAY_6:
        script: *launcher_script
        script_md5: *launcher_script_md5
        parameters:
            stage: DAY_6
            <<: *bonsai_launcher_parameters
            stimulus_table_duration: 00:08:00

    DAY_7:
        script: *launcher_script
        script_md5: *launcher_script_md5
        parameters:
            stage: DAY_7
            <<: *bonsai_launcher_parameters
            stimulus_table_duration: 00:18:00

    DAY_8:
        script: *launcher_script
        script_md5: *launcher_script_md5
        parameters:
            stage: DAY_8
            <<: *bonsai_launcher_parameters
            stimulus_table_duration: 00:28:00

    DAY_9:
        script: *launcher_script
        script_md5: *launcher_script_md5
        parameters:
            stage: DAY_9
            <<: *bonsai_launcher_parameters
            stimulus_table_duration: 00:38:00

    DAY_10:
        script: *launcher_script
        script_md5: *launcher_script_md5
        parameters:
            stage: DAY_10
            <<: *bonsai_launcher_parameters
            stimulus_table_duration: 00:48:00

    TRAIN_FULL_DAY1_5:
        script: *launcher_script
        script_md5: *launcher_script_md5
        parameters:
            stage: TRAIN_FULL_DAY1_5
            <<: *bonsai_launcher_parameters
            stimulus_table_duration: 02:00:00

    TEST_CLUSTER:
        script: *launcher_script
        script_md5: *launcher_script_md5
        parameters:
            stage: TEST_CLUSTER
            <<: *bonsai_launcher_parameters
            stimulus_table_duration: 00:05:00
