_snr_0_script: &snr_0_script http://stash.corp.alleninstitute.org/projects/VB/repos/visual_behavior_scripts/raw/passive/snr/ten_session_movies/TenSessionClips_0.py?at=80c313d7bfdbef7b773b2a0e4e1bb1c0760666dc

_snr_0_script_md5: &snr_0_script_md5 2155507d769943fbf1a7250cd537643c

_snr_1_script: &snr_1_script http://stash.corp.alleninstitute.org/projects/VB/repos/visual_behavior_scripts/raw/passive/snr/ten_session_movies/TenSessionClips_1.py?at=80c313d7bfdbef7b773b2a0e4e1bb1c0760666dc

_snr_1_script_md5: &snr_1_script_md5 0fef76857526dd89cc7f57a4daf185f6

_snr_2_script: &snr_2_script http://stash.corp.alleninstitute.org/projects/VB/repos/visual_behavior_scripts/raw/passive/snr/ten_session_movies/TenSessionClips_2.py?at=80c313d7bfdbef7b773b2a0e4e1bb1c0760666dc

_snr_2_script_md5: &snr_2_script_md5 4bc1e2f973400b2d35eff6c867f32194

_snr_3_script: &snr_3_script http://stash.corp.alleninstitute.org/projects/VB/repos/visual_behavior_scripts/raw/passive/snr/ten_session_movies/TenSessionClips_3.py?at=80c313d7bfdbef7b773b2a0e4e1bb1c0760666dc

_snr_3_script_md5: &snr_3_script_md5 ac644977b500dd0e18d81d86c2cce09f

_snr_4_script: &snr_4_script http://stash.corp.alleninstitute.org/projects/VB/repos/visual_behavior_scripts/raw/passive/snr/ten_session_movies/TenSessionClips_4.py?at=80c313d7bfdbef7b773b2a0e4e1bb1c0760666dc

_snr_4_script_md5: &snr_4_script_md5 fcdced25f5367825423919bf23abed1d

_snr_5_script: &snr_5_script http://stash.corp.alleninstitute.org/projects/VB/repos/visual_behavior_scripts/raw/passive/snr/ten_session_movies/TenSessionClips_5.py?at=80c313d7bfdbef7b773b2a0e4e1bb1c0760666dc

_snr_5_script_md5: &snr_5_script_md5 9947b51277c12f1fa6bd643212e16e1c

_snr_6_script: &snr_6_script http://stash.corp.alleninstitute.org/projects/VB/repos/visual_behavior_scripts/raw/passive/snr/ten_session_movies/TenSessionClips_6.py?at=80c313d7bfdbef7b773b2a0e4e1bb1c0760666dc

_snr_6_script_md5: &snr_6_script_md5 dc8fc5c67d2fc18e05fe0fe1e00beb33

_snr_7_script: &snr_7_script http://stash.corp.alleninstitute.org/projects/VB/repos/visual_behavior_scripts/raw/passive/snr/ten_session_movies/TenSessionClips_7.py?at=80c313d7bfdbef7b773b2a0e4e1bb1c0760666dc

_snr_7_script_md5: &snr_7_script_md5 f8ae478c4f88d2a45da7bb66c5b6aaf4

_snr_8_script: &snr_8_script http://stash.corp.alleninstitute.org/projects/VB/repos/visual_behavior_scripts/raw/passive/snr/ten_session_movies/TenSessionClips_8.py?at=80c313d7bfdbef7b773b2a0e4e1bb1c0760666dc

_snr_8_script_md5: &snr_8_script_md5 5bc4e42d79c97966c347b4f004948dec

_snr_9_script: &snr_9_script http://stash.corp.alleninstitute.org/projects/VB/repos/visual_behavior_scripts/raw/passive/snr/ten_session_movies/TenSessionClips_9.py?at=80c313d7bfdbef7b773b2a0e4e1bb1c0760666dc

_snr_9_script_md5: &snr_9_script_md5 4663c6546145474e40e647d422fb09a0

### mtrain definitions

name: VisualCoding_Snr_v1.0.1

transitions:
  - trigger: manual
    source: SNR_0
    dest: SNR_1

  - trigger: manual
    source: SNR_1
    dest: SNR_2

  - trigger: manual
    source: SNR_2
    dest: SNR_3

  - trigger: manual
    source: SNR_3
    dest: SNR_4

  - trigger: manual
    source: SNR_4
    dest: SNR_5

  - trigger: manual
    source: SNR_5
    dest: SNR_6

  - trigger: manual
    source: SNR_6
    dest: SNR_7

  - trigger: manual
    source: SNR_7
    dest: SNR_8

  - trigger: manual
    source: SNR_8
    dest: SNR_9

stages:
  SNR_0:
    script: *snr_0_script
    script_md5: *snr_0_script_md5
    parameters:
      stage: SNR_0

  SNR_1:
    script: *snr_1_script
    script_md5: *snr_1_script_md5
    parameters:
      stage: SNR_1

  SNR_2:
    script: *snr_2_script
    script_md5: *snr_2_script_md5
    parameters:
      stage: SNR_2

  SNR_3:
    script: *snr_3_script
    script_md5: *snr_3_script_md5
    parameters:
      stage: SNR_3

  SNR_4:
    script: *snr_4_script
    script_md5: *snr_4_script_md5
    parameters:
      stage: SNR_4

  SNR_5:
    script: *snr_5_script
    script_md5: *snr_5_script_md5
    parameters:
      stage: SNR_5

  SNR_6:
    script: *snr_6_script
    script_md5: *snr_6_script_md5
    parameters:
      stage: SNR_6

  SNR_7:
    script: *snr_7_script
    script_md5: *snr_7_script_md5
    parameters:
      stage: SNR_7

  SNR_8:
    script: *snr_8_script
    script_md5: *snr_8_script_md5
    parameters:
      stage: SNR_8

  SNR_9:
    script: *snr_9_script
    script_md5: *snr_9_script_md5
    parameters:
      stage: SNR_9
