_script: &script 
  https://raw.githubusercontent.com/samgale/DynamicRoutingTask/81939eb24fd524aa2a889bfd3231b819dc405ad7/runTask.py
_script_md5: 4d531a8ffafeaa6999c0314ed057669b
_parameters: &parameters
  mtrain_translator: dynamic_routing
  task_script_commit_hash: 81939eb24fd524aa2a889bfd3231b819dc405ad7
  task_control_commit_hash: 81939eb24fd524aa2a889bfd3231b819dc405ad7
  GHTaskScriptParams:
    taskScript: 
      https://raw.githubusercontent.com/mochic/DynamicRoutingTask/81939eb24fd524aa2a889bfd3231b819dc405ad7/DynamicRouting1.py
    taskControl: 
      https://raw.githubusercontent.com/mochic/DynamicRoutingTask/81939eb24fd524aa2a889bfd3231b819dc405ad7/TaskControl.py
### mtrain definitions
name: DynamicRouting_rewardOnly_v0.0.1
transitions:
- trigger: progress
  source: STAGE_5_ORI_AMN_MOVING_REWARDONLY
  dest: STAGE_5_AMN_ORI_MOVING_REWARDONLY
- trigger: progress
  source: STAGE_5_AMN_ORI_MOVING_REWARDONLY
  dest: STAGE_5_ORI_AMN_MOVING_REWARDONLY
stages:
  STAGE_5_ORI_AMN_MOVING_REWARDONLY:
    script: *script
    script_md5: 4d531a8ffafeaa6999c0314ed057669b
    parameters:
      <<: *parameters
      stage: STAGE_5_ORI_AMN_MOVING_REWARDONLY
      taskVersion: stage 5 ori AMN moving rewardOnly
  STAGE_5_AMN_ORI_MOVING_REWARDONLY:
    script: *script
    script_md5: 4d531a8ffafeaa6999c0314ed057669b
    parameters:
      <<: *parameters
      stage: STAGE_5_AMN_ORI_MOVING_REWARDONLY
      taskVersion: stage 5 AMN ori moving rewardOnly