_script_0: &script_0 \\allen\programs\mindscope\workgroups\learning\pilots\camstim\stage_1_short_test.py
#/allen/programs/mindscope/workgroups/learning/pilots/camstim/stage_1_short_test.py
_script_0_md5: &script_0_md5 ebd372ce680907b5d5649415b37185c7


_script_1: &script_1 \\allen\programs\mindscope\workgroups\learning\pilots\camstim\stage_1_short.py
#/allen/programs/mindscope/workgroups/learning/pilots/camstim/stage_1_short.py
_script_1_md5: &script_1_md5 da3c2e2cbfb1a93ebbb7f39826b23307


### mtrain definitions
#based on omFISH_Ophys_test_v0.0.1
name: lamf_test_v0.0.0

stages:
  STAGE_1_SHORT_TEST:
    script: *script_0
    script_md5: *script_0_md5
    parameters:
      stage: STAGE_1_SHORT_TEST

  STAGE_1_SHORT:
    script: *script_1
    script_md5: *script_1_md5
    parameters:
      stage: STAGE_1_SHORT
