_change_detection_script: &change_detection_script http://stash.corp.alleninstitute.org/projects/VB/repos/visual_behavior_scripts/raw/phase4/phase4_1.py?at=3bdcd200ba2de261e39acc29f326f1ec68148c7f

_change_detection_script_md5: &change_detection_script_md5 8b33c772f48bfe41d73109e786406c32

_movie_clips_script: &movie_clips_script http://stash.corp.alleninstitute.org/projects/VB/repos/visual_behavior_scripts/raw/receptive_field_mapping.py?at=46ae5481552b2ab22ffa580260426399ae40ffba

_movie_clips_script_md5: &movie_clips_script_md5 8cab71e3cf5acdeef9a4660b09e52798

_T0_full_field_gratings_stimulus: &T0_full_field_gratings
  class: grating
  params:
    tex: sin
    phase: 0
    pre_flash: 
      phase_shift: 0
    sf: 0.08
    contrast: 0.95
    size: 150
    pos: [0,0]
    texRes: '256'
    units: deg
    stim_off_after_change: false    
  groups:
    home:
      Ori: [0]
    change_ori:
      Ori: [90]

_T1_full_field_gratings_stimulus: &T1_full_field_gratings
  class: grating
  params:
    tex: sin
    phase: 0
    pre_flash: 
      phase_shift: 0
    sf: 0.08
    contrast: 0.95
    size: 150
    pos: [0,0]
    texRes: '256'
    units: deg
    stim_off_after_change: true    
  groups:
    home:
      Ori: [0]
    change_ori:
      Ori: [90]

_T2_masked_gratings_stimulus: &T2_masked_gratings
  class: grating
  params:
    tex: sin
    phase: 0
    pre_flash: 
      phase_shift: 0
    sf: 0.08
    contrast: 0.95
    size: 150
    pos: [0,0]
    texRes: '256'
    units: deg
    stim_off_after_change: true
    mask: raisedCos
    maskParams:
      fringeWidth: 0.1
  groups:
    home:
      Ori: [0]
    change_ori:
      Ori: [90]

_T3_masked_gratings_stimulus: &T3_masked_gratings
  class: grating
  params:
    tex: sin
    phase: 0
    pre_flash: 
      phase_shift: 0.5
    sf: 0.08
    contrast: 0.95
    size: 60
    pos: [0,0]
    texRes: '256'
    units: deg
    stim_off_after_change: true
    mask: raisedCos
    maskParams:
      fringeWidth: 0.1
  groups:
    home:
      Ori: [0]
    change_ori:
      Ori: [90]

_T4_masked_gratings_stimulus: &T4_masked_gratings
  class: grating
  params:
    tex: sin
    phase: 0
    pre_flash: 
      phase_shift: 0.5
    sf: 0.08
    contrast: 0.95
    size: 60
    pos: [0,0]
    texRes: '256'
    units: deg
    stim_off_after_change: true
    mask: raisedCos
    maskParams:
      fringeWidth: 0.1
  groups:
    home:
      Ori: [0]
    change_ori:
      Ori: [22, 45, 90, 90]

_T5_masked_gratings_stimulus: &T5_masked_gratings
  class: grating
  params:
    tex: sin
    phase: 0
    pre_flash: 
      phase_shift: 0.5
    sf: 0.08
    contrast: 0.95
    size: 60
    pos: [0,0]
    texRes: '256'
    units: deg
    stim_off_after_change: true
    mask: raisedCos
    maskParams:
      fringeWidth: 0.1
  groups:
    home:
      Ori: [0]
    change_ori:
      Ori: [10, 22, 45]

_T6_masked_gratings_stimulus: &T6_masked_gratings
  class: grating
  params:
    tex: sin
    phase: 0
    pre_flash: 
      phase_shift: 0.5
    sf: 0.08
    contrast: 0.95
    size: 60
    pos: [0,0]
    texRes: '256'
    units: deg
    stim_off_after_change: true
    mask: raisedCos
    maskParams:
      fringeWidth: 0.1
  groups:
    home:
      Ori: [0]
    change_ori:
      Ori: [10, 22, 45]

_mapping_movie_list: &mapping_movie_list
  - name: gabor
    params:
      frame_length: 0.016666666666666666
      movie_path: //allen/programs/braintv/workgroups/nc-ophys/1022/mapping_stim_movies/gabor-remastered-1576117355.npy
      runs: 5 # 1 min each run
      size: [1920, 1080]

  - name: flash
    params:
      frame_length: 0.016666666666666666
      movie_path: //allen/programs/braintv/workgroups/nc-ophys/1022/mapping_stim_movies/flash-remastered-1576272856.npy
      runs: 5 # 1 min each
      size: [1920, 1080]

_flash_parameters: &flash_parameters

  abort_early_response: true
  auto_reward_delay: 0.15
  auto_reward_vol: 0.005
  catch_freq: 0.25
  change_flashes_max: 7
  change_flashes_min: 1
  change_time_dist: geometric
  change_time_scale: 0.3
  dev: false
  end_after_response: true
  end_after_response_sec: 0
  failure_repeats: 5
  free_reward_trials: 10000
  home_pos:
    group: home
    params:
        - param: Ori
          value: [-45, 45]
  initial_blank: 0.0
  max_task_duration_min: 60.0
  min_no_lick_time: 0.0
  no_stim_no_lick_randrange: [3,5]
  periodic_flash: [0.25, 0.5]
  pre_change_time: 1.0
  prechange_no_lick_duration: 0.75
  response_window: [0.15, 0.75]
  reward_volume: 0.005
  start_padding_windowless: 0.0
  start_stop_padding: 1.0
  stimulus_window: 6.0
  stimulus_window_no_lick: 0
  task_id: DoC-2
  timeout_duration: 0.3
  volume_limit: 5.0
  warm_up_trials: 0

  # start stop padding < 1 can cause a critcally breaking bug
  start_stop_padding: 1

_no_flash_parameters: &no_flash_parameters
  <<: *flash_parameters
  periodic_flash: null
  response_window: [0.15, 1.0]
  reward_volume: 0.005
  free_reward_trials: 10
  pre_change_time: 2.25

  # timing of changes
  change_time_dist: exponential
  change_time_scale: 2.0
  change_flashes_min: null
  change_flashes_max: null

### mtrain definitions
#based on VisualBehavior_Task1A_v1.0.3
name: phase4_1_v0.0.0

transitions:
  - trigger: progress
    source: TRAINING_0
    dest: TRAINING_1
    conditions: one_complete

  - trigger: progress
    source: TRAINING_1
    dest: TRAINING_2
    conditions: [two_out_of_three_aint_bad, yesterday_was_good]

  - trigger: progress
    source: TRAINING_2
    dest: TRAINING_3
    conditions: [two_out_of_three_aint_bad, yesterday_was_good]

  - trigger: progress
    source: TRAINING_3
    dest: TRAINING_4
    conditions: three_complete

  - trigger: progress
    source: TRAINING_4
    dest: TRAINING_5
    conditions: meets_engagement_criteria

  - trigger: progress
    source: TRAINING_5
    dest: TRAINING_6_handoff
    conditions: [meets_engagement_criteria, meets_hit_threshold]

  - trigger: progress
    source: TRAINING_6_handoff
    dest: TRAINING_5_lapsed
    unless: [meets_engagement_criteria, meets_hit_threshold]

  - trigger: progress
    source: TRAINING_5_lapsed
    dest: TRAINING_6_handoff
    conditions: [meets_engagement_criteria, meets_hit_threshold]

  - trigger: manual
    source: TRAINING_6_handoff
    dest: HABITUATION

  - trigger: manual
    source: HABITUATION
    dest: EPHYS

stages:
  TRAINING_0:
    script: *change_detection_script
    script_md5: *change_detection_script_md5
    parameters:
      <<: *no_flash_parameters
      stage: TRAINING_0
      stimulus: *T0_full_field_gratings

      # auto rewards
      warm_up_trials: -1 #infinite
      abort_on_early_response: False
      catch_frequency: 0.0

      response_window: [0.0, 0.0]
      min_no_lick_time: 0.0
      failure_repeats: 0

      # trial timing
      max_task_duration_min: 15.0

      # rewards (mL)
      reward_volume: 0.0

      # appears to be necessary to avoid potential race conditions on first trial
      start_stop_padding: 1.0

      # ephys-specific no grayscreen pre-exp time
      start_padding_windowless: 1.0

  TRAINING_1:
    script: *change_detection_script
    script_md5: *change_detection_script_md5
    parameters:
      <<: *no_flash_parameters
      stage: TRAINING_1
      stimulus: *T1_full_field_gratings

      # ephys-specific no grayscreen pre-exp time
      start_padding_windowless: 20.0

  TRAINING_2:
    script: *change_detection_script
    script_md5: *change_detection_script_md5
    parameters:
      <<: *flash_parameters
      stage: TRAINING_2
      stimulus: *T2_masked_gratings

  TRAINING_3:
    script: *change_detection_script
    script_md5: *change_detection_script_md5
    parameters:
      <<: *flash_parameters
      stage: TRAINING_3
      stimulus: *T3_masked_gratings
      

  TRAINING_4:
    script: *change_detection_script
    script_md5: *change_detection_script_md5
    parameters:
      <<: *flash_parameters
      stage: TRAINING_4
      stimulus: *T4_masked_gratings

  TRAINING_5:
    script: *change_detection_script
    script_md5: *change_detection_script_md5
    parameters:
      <<: *flash_parameters
      stage: TRAINING_5
      stimulus: *T5_masked_gratings

  TRAINING_6_handoff:
    script: *change_detection_script
    script_md5: *change_detection_script_md5
    parameters:
      <<: *flash_parameters
      stage: TRAINING_6_handoff
      stimulus: *T6_masked_gratings
      
  TRAINING_5_lapsed:
    script: *change_detection_script
    script_md5: *change_detection_script_md5
    parameters:
      <<: *flash_parameters
      stage: TRAINING_5_lapsed
      stimulus: *T5_masked_gratings

  HABITUATION:
    script: *change_detection_script
    script_md5: *change_detection_script_md5
    parameters:
      <<: *flash_parameters
      stage: HABITUATION
      stimulus: *T6_masked_gratings
      
      # play list of movies mimicking a mapping session
      epilogue_list: *mapping_movie_list

  EPHYS:
    script: *change_detection_script
    script_md5: *change_detection_script_md5
    parameters:
      <<: *flash_parameters
      stage: EPHYS
      stimulus: *T6_masked_gratings
      
