_passive_prod_ephys_script: &passive_prod_ephys_script http://stash.corp.alleninstitute.org/users/jeromel/repos/openscope-barcodingstim/raw/test-scripts/production_script.py?at=4493e5325371ee479e4470de1d6d9258a289af62
_passive_prod_ephys_script_md5: &passive_prod_ephys_script_md5 6f8db958792b5ab3a24efc2d42bc2d49

_optotagging_script: &optotagging_script http://stash.corp.alleninstitute.org/users/jeromel/repos/openscope-glo-stim/raw/pilot-scripts-allen/opto-tagging-only.py?at=f2edcca4c41f9a780ba564499809672748b53bf0
_optotagging_script_md5: &optotagging_script_md5 acab6e90112a1ec23adc25bea5406a5f

### mtrain definitions
name: Openscope_Barcoding_v7

transitions:
  - trigger: progress
    source: PASSIVE_CLUSTER_HAB_10MIN_DAY6
    dest: PASSIVE_CLUSTER_HAB_20MIN_DAY7
    conditions: one_complete

  - trigger: progress
    source: PASSIVE_CLUSTER_HAB_20MIN_DAY7
    dest: PASSIVE_CLUSTER_HAB_30MIN_DAY8
    conditions: one_complete

  - trigger: progress
    source: PASSIVE_CLUSTER_HAB_30MIN_DAY8
    dest: PASSIVE_CLUSTER_HAB_40MIN_DAY9
    conditions: one_complete

  - trigger: progress
    source: PASSIVE_CLUSTER_HAB_40MIN_DAY9
    dest: PASSIVE_CLUSTER_HAB_50MIN_DAY10
    conditions: one_complete
  
  - trigger: manual
    source: PASSIVE_CLUSTER_HAB_50MIN_DAY10
    dest: PASSIVE_EPHYS_HAB_60MIN_DAY1_2

  - trigger: manual
    source: PASSIVE_EPHYS_HAB_60MIN_DAY1_2
    dest: PASSIVE_EPHYS_HAB_90MIN_DAY3_4

  - trigger: manual
    source: PASSIVE_EPHYS_HAB_90MIN_DAY3_4
    dest: PASSIVE_EPHYS_HAB_120MIN_DAY5

  - trigger: manual
    source: PASSIVE_EPHYS_HAB_120MIN_DAY5
    dest: PASSIVE_EPHYS_PROD_120MIN_DAY1

  - trigger: manual
    source: PASSIVE_EPHYS_PROD_120MIN_DAY1
    dest: OPTOTAGGING_ONLY

stages:
  PASSIVE_CLUSTER_HAB_10MIN_DAY6:
    script: *passive_prod_ephys_script
    script_md5: *passive_prod_ephys_script_md5
    parameters:
      stage: PASSIVE_CLUSTER_HAB_10MIN_DAY6
      add_flashes: True
      add_static: True
      add_drift: True
      add_rf: True
      number_runs_rf: 1
      n_repeats: 2
      monitor_name: "Gamma1.Luminance50"
      data_folder: //allen/programs/mindscope/workgroups/openscope/2023-Barcoding/openscope-barcodingstim/test-scripts

      # optotagging      
      disable_opto: True

      opto_params: 
        operation_mode: "experiment"

  PASSIVE_CLUSTER_HAB_20MIN_DAY7:
    script: *passive_prod_ephys_script
    script_md5: *passive_prod_ephys_script_md5
    parameters:
      stage: PASSIVE_CLUSTER_HAB_20MIN_DAY7
      add_flashes: True
      add_static: True
      add_drift: True
      add_rf: True
      number_runs_rf: 2
      n_repeats: 4
      monitor_name: "Gamma1.Luminance50"
      data_folder: //allen/programs/mindscope/workgroups/openscope/2023-Barcoding/openscope-barcodingstim/test-scripts

      # optotagging      
      disable_opto: True

      opto_params: 
        operation_mode: "experiment"

  PASSIVE_CLUSTER_HAB_30MIN_DAY8:
    script: *passive_prod_ephys_script
    script_md5: *passive_prod_ephys_script_md5
    parameters:
      stage: PASSIVE_CLUSTER_HAB_30MIN_DAY8
      add_flashes: True
      add_static: True
      add_drift: True
      add_rf: True
      number_runs_rf: 3
      n_repeats: 6
      monitor_name: "Gamma1.Luminance50"
      data_folder: //allen/programs/mindscope/workgroups/openscope/2023-Barcoding/openscope-barcodingstim/test-scripts

      disable_opto: True

      opto_params: 
        operation_mode: "experiment"

  PASSIVE_CLUSTER_HAB_40MIN_DAY9:
    script: *passive_prod_ephys_script
    script_md5: *passive_prod_ephys_script_md5
    
    parameters:
      stage: PASSIVE_CLUSTER_HAB_40MIN_DAY9
      add_flashes: True
      add_static: True
      add_drift: True
      add_rf: True
      number_runs_rf: 4
      n_repeats: 8
      monitor_name: "Gamma1.Luminance50"
      data_folder: //allen/programs/mindscope/workgroups/openscope/2023-Barcoding/openscope-barcodingstim/test-scripts

      # optotagging      
      disable_opto: True

      opto_params: 
        operation_mode: "experiment"

  PASSIVE_CLUSTER_HAB_50MIN_DAY10:
    script: *passive_prod_ephys_script
    script_md5: *passive_prod_ephys_script_md5

    parameters:
      stage: PASSIVE_CLUSTER_HAB_50MIN_DAY10
      add_flashes: True
      add_static: True
      add_drift: True
      add_rf: True
      number_runs_rf: 5
      n_repeats: 10
      monitor_name: "Gamma1.Luminance50"
      data_folder: //allen/programs/mindscope/workgroups/openscope/2023-Barcoding/openscope-barcodingstim/test-scripts

      # optotagging      
      disable_opto: True

      opto_params: 
        operation_mode: "experiment"

  PASSIVE_EPHYS_HAB_60MIN_DAY1_2:
    script: *passive_prod_ephys_script
    script_md5: *passive_prod_ephys_script_md5

    parameters:
      stage: PASSIVE_EPHYS_HAB_60MIN_DAY1_2
      add_flashes: True
      add_static: True
      add_drift: True
      add_rf: True
      number_runs_rf: 6
      n_repeats: 12
      monitor_name: "Gamma1.Luminance50"
      data_folder: //allen/programs/mindscope/workgroups/openscope/2023-Barcoding/openscope-barcodingstim/test-scripts

      # optotagging      
      disable_opto: True

      opto_params: 
        operation_mode: "experiment"

  PASSIVE_EPHYS_HAB_90MIN_DAY3_4:
    script: *passive_prod_ephys_script
    script_md5: *passive_prod_ephys_script_md5

    parameters:
      stage: PASSIVE_EPHYS_HAB_90MIN_DAY3_4
      add_flashes: True
      add_static: True
      add_drift: True
      add_rf: True
      number_runs_rf: 8
      n_repeats: 18
      monitor_name: "Gamma1.Luminance50"
      data_folder: //allen/programs/mindscope/workgroups/openscope/2023-Barcoding/openscope-barcodingstim/test-scripts

      # optotagging      
      disable_opto: True

      opto_params: 
        operation_mode: "experiment"
      
  PASSIVE_EPHYS_HAB_120MIN_DAY5:
    script: *passive_prod_ephys_script
    script_md5: *passive_prod_ephys_script_md5

    parameters:
      stage: PASSIVE_EPHYS_HAB_120MIN_DAY5
      add_flashes: True
      add_static: True
      add_drift: True
      add_rf: True
      number_runs_rf: 8
      n_repeats: 24
      monitor_name: "Gamma1.Luminance50"
      data_folder: //allen/programs/mindscope/workgroups/openscope/2023-Barcoding/openscope-barcodingstim/test-scripts

      # optotagging      
      disable_opto: True

      opto_params: 
        operation_mode: "experiment"


  PASSIVE_EPHYS_PROD_120MIN_DAY1:
    script: *passive_prod_ephys_script
    script_md5: *passive_prod_ephys_script_md5

    parameters:
      stage: PASSIVE_EPHYS_PROD_120MIN_DAY1
      add_flashes: True
      add_static: True
      add_drift: True
      add_rf: True
      number_runs_rf: 8
      n_repeats: 24
      monitor_name: "Gamma1.Luminance50"
      data_folder: //allen/programs/mindscope/workgroups/openscope/2023-Barcoding/openscope-barcodingstim/test-scripts

      # optotagging      
      disable_opto: False

      opto_params: 
        operation_mode: "experiment"

  OPTOTAGGING_ONLY:
    script: *optotagging_script
    script_md5: *optotagging_script_md5
    parameters:
      add_flashes: False
      add_static: False
      add_drift: False
      add_rf: False
      number_runs_rf: 1
      n_repeats: 1
      monitor_name: "Gamma1.Luminance50"
      data_folder: //allen/programs/mindscope/workgroups/openscope/2023-Barcoding/openscope-barcodingstim/test-scripts
      
      stage: OPTOTAGGING_ONLY

      # optotagging      
      disable_opto: False

      opto_params: 
        operation_mode: "experiment"