_passive_prod_circle_script: &passive_prod_circle_script http://stash.corp.alleninstitute.org/users/jeromel/repos/consciousness-circlestim/raw/circle_stim.py?at=c112b94d4249aec8b69a7d2d0557cb801d28d0bd
_passive_prod_circle_script_md5: &passive_prod_circle_script_md5 49b82e36b6dabc10fb9b96243651befb

### mtrain definitions
name: consciousness_circle_v4

transitions:
  - trigger: manual
    source: PASSIVE_CIRCLE
    dest: PASSIVE_CIRCLE
    
stages:
  PASSIVE_CIRCLE:
    script: *passive_prod_circle_script
    script_md5: *passive_prod_circle_script_md5
    parameters:
      stage: PASSIVE_CIRCLE
      monitor_name: "Gamma1.Luminance50"