_day_1_script: &day_1_script
    http://stash.corp.alleninstitute.org/projects/VB/repos/visual_behavior_scripts/raw/passive/visual_coding/day1.py?at=e4b0f5cc22aa94d5ee2d0916b0db1a1afa774888

_day_1_script_md5: &day_1_script_md5
    1284dde1bab18233f470a679d5a234f2

_day_2_script: &day_2_script
    http://stash.corp.alleninstitute.org/projects/VB/repos/visual_behavior_scripts/raw/passive/visual_coding/day2.py?at=e4b0f5cc22aa94d5ee2d0916b0db1a1afa774888

_day_2_script_md5: &day_2_script_md5
    5bd554df9c9bd5c40485a07956273cd9
    
_day_3_script: &day_3_script
    http://stash.corp.alleninstitute.org/projects/VB/repos/visual_behavior_scripts/raw/passive/visual_coding/day3.py?at=e4b0f5cc22aa94d5ee2d0916b0db1a1afa774888

_day_3_script_md5: &day_3_script_md5
    505ef9e14e6ac3f80e691f4d0b5265a8
    
_day_4_script: &day_4_script
    http://stash.corp.alleninstitute.org/projects/VB/repos/visual_behavior_scripts/raw/passive/visual_coding/day4.py?at=e4b0f5cc22aa94d5ee2d0916b0db1a1afa774888

_day_4_script_md5: &day_4_script_md5
    d82360a405c9ba1f1cc1d59b7707bc80
    
_day_5_script: &day_5_script
    http://stash.corp.alleninstitute.org/projects/VB/repos/visual_behavior_scripts/raw/passive/visual_coding/day5.py?at=e4b0f5cc22aa94d5ee2d0916b0db1a1afa774888

_day_5_script_md5: &day_5_script_md5
    e53821b4b498bcecb4aa793e5dff67b5
    
_day_6_script: &day_6_script
    http://stash.corp.alleninstitute.org/projects/VB/repos/visual_behavior_scripts/raw/passive/visual_coding/day6.py?at=e4b0f5cc22aa94d5ee2d0916b0db1a1afa774888

_day_6_script_md5: &day_6_script_md5
    b7e1e4e06b3736d04dafaa64793dee42

### mtrain definitions
#based on VisualBehavior_Task1A_v1.0.3
name: Passive_VisualCoding_v1.0.0

transitions:

  - trigger: progress
    source: DAY_1
    dest: DAY_2
    conditions: one_complete

  - trigger: progress
    source: DAY_2
    dest: DAY_3
    conditions: one_complete

  - trigger: progress
    source: DAY_3
    dest: DAY_4
    conditions: one_complete

  - trigger: progress
    source: DAY_4
    dest: DAY_5
    conditions: one_complete

  - trigger: progress
    source: DAY_5
    dest: DAY_6
    conditions: one_complete

stages:
    DAY_1:
        script: *day_1_script
        script_md5: *day_1_script_md5
        parameters:
            stage: DAY_1

    DAY_2:
        script: *day_2_script
        script_md5: *day_2_script_md5
        parameters:
            stage: DAY_2

    DAY_3:
        script: *day_3_script
        script_md5: *day_3_script_md5
        parameters:
            stage: DAY_3

    DAY_4:
        script: *day_4_script
        script_md5: *day_4_script_md5
        parameters:
            stage: DAY_4

    DAY_5:
        script: *day_5_script
        script_md5: *day_5_script_md5
        parameters:
            stage: DAY_5

    DAY_6:
        script: *day_6_script
        script_md5: *day_6_script_md5
        parameters:
            stage: DAY_6
    
