_change_detection_script: &change_detection_script http://stash.corp.alleninstitute.org/projects/VB/repos/visual_behavior_scripts/raw/change_detection_extended.py?at=2ff2dc9e4393b81ba2d831cd07ca247dbef84aeb

_change_detection_script_md5: &change_detection_script_md5 9c18779b269d9ffaf4760b218cadc5a1

_movie_clips_script: &movie_clips_script http://stash.corp.alleninstitute.org/projects/VB/repos/visual_behavior_scripts/raw/receptive_field_mapping.py?at=46ae5481552b2ab22ffa580260426399ae40ffba

_movie_clips_script_md5: &movie_clips_script_md5 8cab71e3cf5acdeef9a4660b09e52798

_replay_script: &replay_script http://stash.corp.alleninstitute.org/projects/VB/repos/visual_behavior_scripts/raw/replay_session/triscript.py?at=58c191f1ca012fcfb38558691d66b23da102f664

_replay_script_md5: &replay_script_md5 ee0f394c15f7d7037eb2dfc0a9dc4fd0

_full_field_gratings_stimulus: &full_field_gratings
  class: grating
  params:
    sf: 0.04
    tex: sqr
    size: [200, 150]
    units: deg
    phase: 0.25
  groups:
    vertical:
      Ori: [0, 180]
    horizontal:
      Ori: [90, 270]

_image_set_g_stimulus: &image_set_g
  class: images
  luminance_matching_intensity: -0.46
  params:
    image_set: //allen/programs/braintv/workgroups/nc-ophys/visual_behavior/image_dictionaries/Natural_Images_Lum_Matched_set_ophys_G_2019.05.26.pkl
    sampling: even

_image_set_h_stimulus: &image_set_h
  class: images
  luminance_matching_intensity: -0.46
  params:
    image_set: //allen/programs/braintv/workgroups/nc-ophys/visual_behavior/image_dictionaries/Natural_Images_Lum_Matched_set_ophys_H_2019.05.26.pkl
    sampling: even

_mapping_movie_list: &mapping_movie_list
  - name: gabor
    params:
      frame_length: 0.016666666666666666
      movie_path: //allen/programs/braintv/workgroups/nc-ophys/1022/mapping_stim_movies/gabor-remastered-1576117355.npy
      runs: 5 # 1 min each run
      size: [1920, 1080]

  - name: flash
    params:
      frame_length: 0.016666666666666666
      movie_path: //allen/programs/braintv/workgroups/nc-ophys/1022/mapping_stim_movies/flash-remastered-1576272856.npy
      runs: 5 # 1 min each
      size: [1920, 1080]

_flash_parameters: &flash_parameters
  task_id: DoC

  catch_frequency: 0.25
  failure_repeats: 5

  # rewards (mL)
  reward_volume: 0.007
  volume_limit: 5.0

  # auto rewards
  auto_reward_vol: 0.005
  warm_up_trials: 5
  auto_reward_delay: 0.150
  free_reward_trials: 10000

  # trial timing
  min_no_lick_time: 0.0
  timeout_duration: 0.3
  pre_change_time: 0.0
  stimulus_window: 6.0
  max_task_duration_min: 60.0
  periodic_flash: [0.25, 0.5]
  response_window: [0.15, 0.75]
  end_after_response: True
  end_after_response_sec: 3.5

  # timing of changes
  change_time_dist: geometric
  change_time_scale: 0.3
  change_flashes_min: 4 # inclusive
  change_flashes_max: 12 # exclusive

  # start stop padding < 1 can cause a critcally breaking bug
  start_stop_padding: 1

_no_flash_parameters: &no_flash_parameters
  <<: *flash_parameters
  periodic_flash: null
  response_window: [0.15, 1.0]
  reward_volume: 0.010
  free_reward_trials: 10
  pre_change_time: 2.25

  # timing of changes
  change_time_dist: exponential
  change_time_scale: 2.0
  change_flashes_min: null
  change_flashes_max: null

_image_set_g_parameters: &image_set_g_parameters
  <<: *flash_parameters
  stimulus: *image_set_g
  catch_frequency: null

_image_set_h_parameters: &image_set_h_parameters
  <<: *flash_parameters
  stimulus: *image_set_h
  catch_frequency: null

_replay_g_parameters: &replay_g_parameters
  <<: *flash_parameters
  stimulus: *image_set_g
  catch_frequency: null
  mapping:
    flash_path: //allen/programs/braintv/workgroups/nc-ophys/1022/replay-stim/flash_250ms.stim
    gabor_path: //allen/programs/braintv/workgroups/nc-ophys/1022/replay-stim/gabor_20_deg_250ms.stim
  output_dir: C:/ProgramData/camstim/output
  agent_socket: "127.0.0.1:5000"

_replay_h_parameters: &replay_h_parameters
  <<: *flash_parameters
  stimulus: *image_set_h
  catch_frequency: null
  mapping:
    flash_path: //allen/programs/braintv/workgroups/nc-ophys/1022/replay-stim/flash_250ms.stim
    gabor_path: //allen/programs/braintv/workgroups/nc-ophys/1022/replay-stim/gabor_20_deg_250ms.stim
  output_dir: C:/ProgramData/camstim/output
  agent_socket: "127.0.0.1:5000"

### mtrain definitions
#based on VisualBehavior_Task1A_v1.0.3
name: VisualBehaviorEPHYS_Task1G_v0.1.2

transitions:
  - trigger: progress
    source: TRAINING_0_gratings_autorewards_15min_0uL_reward
    dest: TRAINING_1_gratings_10uL_reward
    conditions: one_complete

  - trigger: progress
    source: TRAINING_1_gratings_10uL_reward
    dest: TRAINING_2_gratings_flashed_10uL_reward
    conditions: [two_out_of_three_aint_bad, yesterday_was_good]

  - trigger: progress
    source: TRAINING_2_gratings_flashed_10uL_reward
    dest: TRAINING_3_images_G_10uL_reward
    conditions: [two_out_of_three_aint_bad, yesterday_was_good]

  - trigger: progress
    source: TRAINING_3_images_G_10uL_reward
    dest: TRAINING_4_images_G_training_7uL_reward
    conditions: three_complete

  - trigger: progress
    source: TRAINING_4_images_G_training_7uL_reward
    dest: TRAINING_5_images_G_epilogue_5uL_reward
    conditions: meets_engagement_criteria_logged

  - trigger: progress
    source: TRAINING_5_images_G_epilogue_5uL_reward
    dest: TRAINING_5_images_G_handoff_ready_5uL_reward
    conditions: meets_engagement_and_hit_threshold

  - trigger: progress
    source: TRAINING_5_images_G_handoff_ready_5uL_reward
    dest: TRAINING_5_images_G_handoff_lapsed_5uL_reward
    unless: meets_engagement_and_hit_threshold

  - trigger: progress
    source: TRAINING_5_images_G_handoff_lapsed_5uL_reward
    dest: TRAINING_5_images_G_handoff_ready_5uL_reward
    conditions: meets_engagement_and_hit_threshold

  - trigger: manual
    source: TRAINING_5_images_G_handoff_ready_5uL_reward
    dest: HABITUATION_5_images_G_handoff_ready_5uL_reward

  - trigger: manual
    source: HABITUATION_5_images_G_handoff_ready_5uL_reward
    dest: EPHYS_1_images_G_5uL_reward

  - trigger: manual
    source: EPHYS_1_images_G_5uL_reward
    dest: EPHYS_1_images_H_5uL_reward

  - trigger: manual
    source: TRAINING_5_images_G_handoff_ready_5uL_reward
    dest: HABITUATION_5_images_G_handoff_ready_3uL_reward

  - trigger: manual
    source: HABITUATION_5_images_G_handoff_ready_3uL_reward
    dest: EPHYS_1_images_G_3uL_reward

  - trigger: manual
    source: EPHYS_1_images_G_3uL_reward
    dest: EPHYS_1_images_H_3uL_reward

stages:
  TRAINING_0_gratings_autorewards_15min_0uL_reward:
    script: *change_detection_script
    script_md5: *change_detection_script_md5
    parameters:
      <<: *no_flash_parameters
      stage: TRAINING_0_gratings_autorewards_15min_0uL_reward
      stimulus: *full_field_gratings

      # auto rewards
      warm_up_trials: -1 #infinite
      abort_on_early_response: False
      catch_frequency: 0.0

      response_window: [0.0, 0.0]
      min_no_lick_time: 0.0
      failure_repeats: 0

      # trial timing
      max_task_duration_min: 15.0

      # rewards (mL)
      reward_volume: 0.0

      # ephys-specific no grayscreen pre-exp time
      start_padding_windowless: 20.0

  TRAINING_1_gratings_10uL_reward:
    script: *change_detection_script
    script_md5: *change_detection_script_md5
    parameters:
      <<: *no_flash_parameters
      stage: TRAINING_1_gratings_10uL_reward

      stimulus: *full_field_gratings

      # ephys-specific no grayscreen pre-exp time
      start_padding_windowless: 20.0

  TRAINING_2_gratings_flashed_10uL_reward:
    script: *change_detection_script
    script_md5: *change_detection_script_md5
    parameters:
      <<: *flash_parameters
      stage: TRAINING_2_gratings_flashed_10uL_reward
      task_id: DoC

      stimulus: *full_field_gratings
      free_reward_trials: 10

      # rewards (mL)
      reward_volume: 0.01

      # ephys-specific no grayscreen pre-exp time
      start_padding_windowless: 20.0

  TRAINING_3_images_G_10uL_reward:
    script: *change_detection_script
    script_md5: *change_detection_script_md5
    parameters:
      <<: *image_set_g_parameters
      stage: TRAINING_3_images_G_10uL_reward

      # rewards (mL)
      reward_volume: 0.01
      free_reward_trials: 10

      # ephys-specific no grayscreen pre-exp time
      start_padding_windowless: 20.0

  TRAINING_4_images_G_training_7uL_reward:
    script: *change_detection_script
    script_md5: *change_detection_script_md5
    parameters:
      <<: *image_set_g_parameters
      stage: TRAINING_4_images_G_training_7uL_reward

      # ephys-specific no grayscreen pre-exp time
      start_padding_windowless: 20.0

  TRAINING_5_images_G_epilogue_5uL_reward:
    script: *change_detection_script
    script_md5: *change_detection_script_md5
    parameters:
      <<: *image_set_g_parameters
      stage: TRAINING_5_images_G_epilogue_5uL_reward
      warm_up_trials: 5
      reward_volume: 0.005

      # ephys-specific no grayscreen pre-exp time
      start_padding_windowless: 300.0

      # play list of movies mimicking a mapping session
      epilogue_list: *mapping_movie_list

  TRAINING_5_images_G_handoff_ready_5uL_reward:
    script: *change_detection_script
    script_md5: *change_detection_script_md5
    parameters:
      <<: *image_set_g_parameters
      stage: TRAINING_5_images_G_handoff_ready_5uL_reward
      warm_up_trials: 5
      reward_volume: 0.005

      # ephys-specific no grayscreen pre-exp time
      start_padding_windowless: 300.0

      # play list of movies mimicking a mapping session
      epilogue_list: *mapping_movie_list

  TRAINING_5_images_G_handoff_lapsed_5uL_reward:
    script: *change_detection_script
    script_md5: *change_detection_script_md5
    parameters:
      <<: *image_set_g_parameters
      stage: TRAINING_5_images_G_handoff_lapsed_5uL_reward
      warm_up_trials: 5
      reward_volume: 0.005

      # ephys-specific no grayscreen pre-exp time
      start_padding_windowless: 300.0

      # play list of movies mimicking a mapping session
      epilogue_list: *mapping_movie_list

  HABITUATION_5_images_G_handoff_ready_5uL_reward:
    script: *replay_script
    script_md5: *replay_script_md5
    parameters:
      <<: *replay_g_parameters
      stage: HABITUATION_5_images_G_handoff_ready_5uL_reward
      warm_up_trials: 5
      reward_volume: 0.005
      free_reward_trials: 10
      max_mapping_duration_min: 10
      disable_replay: True
      disable_opto: True
      opto_params:
        operation_mode: "experiment"

      # ephys-specific no grayscreen pre-exp time
      start_padding_windowless: 20.0

  EPHYS_1_images_G_5uL_reward:
    script: *replay_script
    script_md5: *replay_script_md5
    parameters:
      <<: *replay_g_parameters
      stage: EPHYS_1_images_G_5uL_reward
      warm_up_trials: 3
      flash_omit_probability: 0.05
      reward_volume: 0.005
      max_mapping_duration_min: 35
      opto_params:
        operation_mode: "experiment"

  EPHYS_1_images_H_5uL_reward:
    script: *replay_script
    script_md5: *replay_script_md5
    parameters:
      <<: *replay_h_parameters
      stage: EPHYS_1_images_H_5uL_reward
      warm_up_trials: 3
      flash_omit_probability: 0.05
      reward_volume: 0.005
      max_mapping_duration_min: 35
      opto_params:
        operation_mode: "experiment"

  HABITUATION_5_images_G_handoff_ready_3uL_reward:
    script: *replay_script
    script_md5: *replay_script_md5
    parameters:
      <<: *replay_g_parameters
      stage: HABITUATION_5_images_G_handoff_ready_3uL_reward
      warm_up_trials: 5
      reward_volume: 0.003
      free_reward_trials: 10
      max_mapping_duration_min: 10
      disable_replay: True
      disable_opto: True
      opto_params:
        operation_mode: "experiment"

      # ephys-specific no grayscreen pre-exp time
      start_padding_windowless: 20.0

  EPHYS_1_images_G_3uL_reward:
    script: *replay_script
    script_md5: *replay_script_md5
    parameters:
      <<: *replay_g_parameters
      stage: EPHYS_1_images_G_3uL_reward
      warm_up_trials: 3
      flash_omit_probability: 0.05
      reward_volume: 0.003
      max_mapping_duration_min: 35
      opto_params:
        operation_mode: "experiment"

  EPHYS_1_images_H_3uL_reward:
    script: *replay_script
    script_md5: *replay_script_md5
    parameters:
      <<: *replay_h_parameters
      stage: EPHYS_1_images_H_3uL_reward
      warm_up_trials: 3
      flash_omit_probability: 0.05
      reward_volume: 0.003
      max_mapping_duration_min: 35
      opto_params:
        operation_mode: "experiment"
