
_change_detection_script: &change_detection_script
    http://foo

_change_detection_script_md5: &change_detection_script_md5
    XXXX

_movie_clips_script: &movie_clips_script
    http://foo

_movie_clips_script_md5: &movie_clips_script_md5
    XXXX

_full_field_gratings_stimulus: &full_field_gratings
    class: grating
    params:
        sf: 0.04
        tex: sqr
        size: [300, 300]
        units: deg
        phase: 0``.25
    groups:
        group0:
            Ori: [0, 180]
        group1:
            Ori: [90, 270]

_image_set_a_stimulus: &image_set_a
    class: images
    params:
        image_set: //allen/aibs/mpe/Software/stimulus_files/nimages_0_20170714.zip
        sampling: even

_image_set_c_stimulus: &image_set_c
    class: images
    params:
        image_set: //allen/aibs/mpe/Software/stimulus_files/nimages_0_20170714.zip
        sampling: even

_flash_parameters: &flash_parameters
    task_id: DoC

    catch_frequency: 0.25
    failure_repeats: 5

    # rewards (mL)
    reward_vol: 0.01
    volume_limit: 5.0

    # auto rewards
    auto_reward_vol: 0.005
    warm_up_trials: 5
    auto_reward_delay: 0.150

    # trial timing
    pre_change_time: 2.25
    stimulus_window: 6.0
    max_task_duration_min: 60.0
    start_stop_padding: 10.0
    periodic_flash: [0.25, 0.5]
    response_window: [0.15,0.75]

_no_flash_parameters: &no_flash_parameters
    <<: *flash_parameters
    periodic_flash: None
    response_window: [0.15,1.0]


_image_set_a_parameters: &image_set_a_parameters
    <<: *flash_parameters
    stimulus: *image_set_a

_image_set_c_parameters: &image_set_c_parameters
    <<: *flash_parameters
    stimulus: *image_set_c


### mtrain definitions

name: v0.1.3

transitions:

  - trigger: progress
    source: 1_AutoRewards
    dest: static_full_field_gratings
    conditions: autorewards_complete

  - trigger: progress
    source: static_full_field_gratings
    dest: static_full_field_gratings_flash_500ms
    conditions: [two_out_of_three_aint_bad, yesterday_was_good]

  - trigger: progress
    source: static_full_field_gratings_flash_500ms
    dest: natural_images
    conditions: [two_out_of_three_aint_bad, yesterday_was_good]

  - trigger: progress
    source: natural_images
    dest: natural_images_drop_reward
    conditions: three_complete

  - trigger: progress
    source: natural_images_drop_reward
    dest: ready_for_imaging
    conditions: meets_engagement_criteria

  - trigger: progress
    source: ready_for_imaging
    dest: not_ready_for_imaging
    unless: meets_engagement_criteria

  - trigger: progress
    source: not_ready_for_imaging
    dest: ready_for_imaging
    conditions: meets_engagement_criteria

  - trigger: handoff
    source: ready_for_imaging
    dest: ophys_set_a
    conditions: meets_engagement_criteria

  - trigger: progress
    source: ophys_set_a
    dest: ophys_set_a_passive
    conditions: four_complete

  - trigger: progress
    source: ophys_set_a_passive
    dest: ophys_set_c
    conditions: one_complete

  - trigger: progress
    source: ophys_set_c
    dest: ophys_set_c_passive
    conditions: four_complete

  - trigger: progress
    source: ophys_set_c_passive
    dest: receptive_field_mapping
    conditions: one_complete

stages:

    1_AutoRewards:
        script: *change_detection_script
        script_md5: *change_detection_script_md5
        parameters:
            <<: *no_flash_parameters
            stage: 1_AutoRewards
            stimulus: *full_field_gratings

            # auto rewards
            warm_up_trials: -1 #infinite
            abort_on_early_response: False

            # trial timing
            max_task_duration_min: 15.0


    static_full_field_gratings:
        script: *change_detection_script
        script_md5: *change_detection_script_md5
        parameters:
            <<: *no_flash_parameters
            stage: static_full_field_gratings

            stimulus: *full_field_gratings


    static_full_field_gratings_flash_500ms:
        script: *change_detection_script
        script_md5: *change_detection_script_md5
        parameters:
            <<: *flash_parameters
            stage: static_full_field_gratings_flash_500ms
            task_id: DoC

            stimulus: *full_field_gratings


    natural_images:
        script: *change_detection_script
        script_md5: *change_detection_script_md5
        parameters:
            <<: *image_set_a_parameters
            stage: natural_images

            # rewards (mL)
            reward_vol: 0.01

    natural_images_drop_reward:
        script: *change_detection_script
        script_md5: *change_detection_script_md5
        parameters:
            <<: *image_set_a_parameters
            stage: natural_images_drop_reward

    ready_for_imaging:
        script: *change_detection_script
        script_md5: *change_detection_script_md5
        parameters:
            <<: *image_set_a_parameters
            stage: ready_for_imaging

    not_ready_for_imaging:
        script: *change_detection_script
        script_md5: *change_detection_script_md5
        parameters:
            <<: *image_set_a_parameters
            stage: not_ready_for_imaging

    ophys_set_a:
        script: *change_detection_script
        script_md5: *change_detection_script_md5
        parameters:
            <<: *image_set_a_parameters
            stage: ophys_set_a

    ophys_set_a_passive:
        script: *change_detection_script
        script_md5: *change_detection_script_md5
        parameters:
            <<: *image_set_a_parameters
            stage: ophys_set_a_passive

    ophys_set_c:
        script: *change_detection_script
        script_md5: *change_detection_script_md5
        parameters:
            <<: *image_set_c_parameters
            stage: ophys_set_c

    ophys_set_c_passive:
        script: *change_detection_script
        script_md5: *change_detection_script_md5
        parameters:
            <<: *image_set_c_parameters
            stage: ophys_set_c_passive
            lick_spout: False

    receptive_field_mapping:
        script: *movie_clips_script
        script_md5: *movie_clips_script_md5
        parameters:
            stage: receptive_field_mapping
