_script_0: &script_0 http://stash.corp.alleninstitute.org/projects/VB/repos/visual_behavior_scripts/raw/testing/TenSessionClips_0.py?at=c0595a7a64f1d01215ff9a94d5fdb676c301f93c

_script_0_md5: &script_0_md5 a6ffc6eb8a39c8c50f01a701fd597b98

_script_1: &script_1 http://stash.corp.alleninstitute.org/projects/VB/repos/visual_behavior_scripts/raw/testing/gratings.py?at=c0595a7a64f1d01215ff9a94d5fdb676c301f93c

_script_1_md5: &script_1_md5 25738fb355c4ce69599b519a3e99ae1b

### mtrain definitions
#based on VisualBehavior_Task1A_v1.0.3
name: omFISH_Ophys_test_v0.0.1

transitions:
  - trigger: manual
    source: STAGE_0
    dest: STAGE_1

stages:
  STAGE_0:
    script: *script_0
    script_md5: *script_0_md5
    parameters:
      stage: STAGE_0
  STAGE_1:
    script: *script_1
    script_md5: *script_1_md5
    parameters:
      stage: STAGE_1
