# dynamic routing task v1 development params
# used for local script development with the camstim v2 api, TODO: add a version number?

_script: &script dynamic_routing.py

_parameters: &parameters
  mtrain_translator: "dynamic_routing"

### mtrain definitions
name: DynamicRoutingTest_v0.0.1

transitions:
  - trigger: manual
    source: STAGE_0
    dest: STAGE_1

stages:
  STAGE_0:
    script: *script
    script_md5: *script # same if script is a resource id
    parameters:
      <<: *parameters
      stage: STAGE_0


  STAGE_1:
    script: *script
    script_md5: *script # same if script is a resource id
    parameters:
      <<: *parameters
      stage: STAGE_1
        