_passive_prod_ephys_script: &passive_prod_ephys_script http://stash.corp.alleninstitute.org/users/jeromel/repos/openscope_vippo_stim/raw/play_stim.py?at=ceae5d16c6b4b853fa92cd7bc4bca7b33e339e9a
_passive_prod_ephys_script_md5: &passive_prod_ephys_script_md5 66733c6f94e6d048f3c395c2141f2758

_optotagging_script: &optotagging_script http://stash.corp.alleninstitute.org/users/jeromel/repos/openscope-glo-stim/raw/pilot-scripts-allen/opto-tagging-only.py?at=f2edcca4c41f9a780ba564499809672748b53bf0
_optotagging_script_md5: &optotagging_script_md5 acab6e90112a1ec23adc25bea5406a5f

### mtrain definitions
name: Openscope_Vippo_v6

transitions:
  - trigger: progress
    source: PASSIVE_CLUSTER_HAB_10MIN_DAY6
    dest: PASSIVE_CLUSTER_HAB_20MIN_DAY7
    conditions: one_complete

  - trigger: progress
    source: PASSIVE_CLUSTER_HAB_20MIN_DAY7
    dest: PASSIVE_CLUSTER_HAB_30MIN_DAY8
    conditions: one_complete

  - trigger: progress
    source: PASSIVE_CLUSTER_HAB_30MIN_DAY8
    dest: PASSIVE_CLUSTER_HAB_40MIN_DAY9
    conditions: one_complete

  - trigger: progress
    source: PASSIVE_CLUSTER_HAB_40MIN_DAY9
    dest: PASSIVE_CLUSTER_HAB_50MIN_DAY10
    conditions: one_complete
  
  - trigger: manual
    source: PASSIVE_CLUSTER_HAB_50MIN_DAY10
    dest: PASSIVE_EPHYS_HAB_60MIN_DAY1_2

  - trigger: manual
    source: PASSIVE_EPHYS_HAB_60MIN_DAY1_2
    dest: PASSIVE_EPHYS_HAB_90MIN_DAY3_4

  - trigger: manual
    source: PASSIVE_EPHYS_HAB_90MIN_DAY3_4
    dest: PASSIVE_EPHYS_HAB_120MIN_DAY5

  - trigger: manual
    source: PASSIVE_EPHYS_HAB_120MIN_DAY5
    dest: PASSIVE_EPHYS_PROD_120MIN_DAY1

  - trigger: manual
    source: PASSIVE_EPHYS_PROD_120MIN_DAY1
    dest: OPTOTAGGING_ONLY

stages:
  PASSIVE_CLUSTER_HAB_10MIN_DAY6:
    script: *passive_prod_ephys_script
    script_md5: *passive_prod_ephys_script_md5
    parameters:
      stage: PASSIVE_CLUSTER_HAB_10MIN_DAY6
      add_rf: True
      number_runs_rf: 1
      n_repeats: 5
      monitor_name: "Gamma1.Luminance50"
      movie_folder: //allen/programs/mindscope/workgroups/openscope/2023-Vippo/openscope_vippo_stim/data

      # optotagging      
      disable_opto: True

      opto_params: 
        operation_mode: "experiment"

  PASSIVE_CLUSTER_HAB_20MIN_DAY7:
    script: *passive_prod_ephys_script
    script_md5: *passive_prod_ephys_script_md5
    parameters:
      stage: PASSIVE_CLUSTER_HAB_20MIN_DAY7
      add_rf: True
      number_runs_rf: 2
      n_repeats: 10
      monitor_name: "Gamma1.Luminance50"
      movie_folder: //allen/programs/mindscope/workgroups/openscope/2023-Vippo/openscope_vippo_stim/data
      # optotagging      
      disable_opto: True

      opto_params: 
        operation_mode: "experiment"

  PASSIVE_CLUSTER_HAB_30MIN_DAY8:
    script: *passive_prod_ephys_script
    script_md5: *passive_prod_ephys_script_md5
    parameters:
      stage: PASSIVE_CLUSTER_HAB_30MIN_DAY8
      add_rf: True
      number_runs_rf: 3
      n_repeats: 15
      monitor_name: "Gamma1.Luminance50"
      movie_folder: //allen/programs/mindscope/workgroups/openscope/2023-Vippo/openscope_vippo_stim/data
      disable_opto: True

      opto_params: 
        operation_mode: "experiment"

  PASSIVE_CLUSTER_HAB_40MIN_DAY9:
    script: *passive_prod_ephys_script
    script_md5: *passive_prod_ephys_script_md5
    
    parameters:
      stage: PASSIVE_CLUSTER_HAB_40MIN_DAY9
      add_rf: True
      number_runs_rf: 4
      n_repeats: 20
      monitor_name: "Gamma1.Luminance50"
      movie_folder: //allen/programs/mindscope/workgroups/openscope/2023-Vippo/openscope_vippo_stim/data
      # optotagging      
      disable_opto: True

      opto_params: 
        operation_mode: "experiment"

  PASSIVE_CLUSTER_HAB_50MIN_DAY10:
    script: *passive_prod_ephys_script
    script_md5: *passive_prod_ephys_script_md5

    parameters:
      stage: PASSIVE_CLUSTER_HAB_50MIN_DAY10
      add_rf: True
      number_runs_rf: 5
      n_repeats: 25
      monitor_name: "Gamma1.Luminance50"
      movie_folder: //allen/programs/mindscope/workgroups/openscope/2023-Vippo/openscope_vippo_stim/data
      # optotagging      
      disable_opto: True

      opto_params: 
        operation_mode: "experiment"

  PASSIVE_EPHYS_HAB_60MIN_DAY1_2:
    script: *passive_prod_ephys_script
    script_md5: *passive_prod_ephys_script_md5

    parameters:
      stage: PASSIVE_EPHYS_HAB_60MIN_DAY1_2
      add_rf: True
      number_runs_rf: 6
      n_repeats: 30
      monitor_name: "Gamma1.Luminance50"
      movie_folder: //allen/programs/mindscope/workgroups/openscope/2023-Vippo/openscope_vippo_stim/data
      # optotagging      
      disable_opto: True

      opto_params: 
        operation_mode: "experiment"

  PASSIVE_EPHYS_HAB_90MIN_DAY3_4:
    script: *passive_prod_ephys_script
    script_md5: *passive_prod_ephys_script_md5

    parameters:
      stage: PASSIVE_EPHYS_HAB_90MIN_DAY3_4
      add_rf: True
      number_runs_rf: 8
      n_repeats: 45
      monitor_name: "Gamma1.Luminance50"
      movie_folder: //allen/programs/mindscope/workgroups/openscope/2023-Vippo/openscope_vippo_stim/data
      # optotagging      
      disable_opto: True

      opto_params: 
        operation_mode: "experiment"
      
  PASSIVE_EPHYS_HAB_120MIN_DAY5:
    script: *passive_prod_ephys_script
    script_md5: *passive_prod_ephys_script_md5

    parameters:
      stage: PASSIVE_EPHYS_HAB_120MIN_DAY5
      add_rf: True
      number_runs_rf: 8
      n_repeats: 60
      monitor_name: "Gamma1.Luminance50"
      movie_folder: //allen/programs/mindscope/workgroups/openscope/2023-Vippo/openscope_vippo_stim/data
      # optotagging      
      disable_opto: True

      opto_params: 
        operation_mode: "experiment"


  PASSIVE_EPHYS_PROD_120MIN_DAY1:
    script: *passive_prod_ephys_script
    script_md5: *passive_prod_ephys_script_md5

    parameters:
      stage: PASSIVE_EPHYS_PROD_120MIN_DAY1
      add_rf: True
      number_runs_rf: 8
      n_repeats: 60
      monitor_name: "Gamma1.Luminance50"
      movie_folder: //allen/programs/mindscope/workgroups/openscope/2023-Vippo/openscope_vippo_stim/data
      # optotagging      
      disable_opto: True

      opto_params: 
        operation_mode: "experiment"

  OPTOTAGGING_ONLY:
    script: *optotagging_script
    script_md5: *optotagging_script_md5
    parameters:
      add_rf: False
      number_runs_rf: 1
      n_repeats: 1
      monitor_name: "Gamma1.Luminance50"
      movie_folder: //allen/programs/mindscope/workgroups/openscope/2023-Vippo/openscope_vippo_stim/data      
      stage: OPTOTAGGING_ONLY

      # optotagging      
      disable_opto: True

      opto_params: 
        operation_mode: "experiment"