_pipeline_script: &pipeline_script http://stash.corp.alleninstitute.org/users/jeromel/repos/openscope_dendritic_coupling/raw/pilot_scripts/full_pipeline_script.py?at=f0e99640a5c3a91667ebfbfd51397201002eebc6
_pipeline_script_md5: &pipeline_script_md5 e62d8d538eda66a019cb982a24337a2f

### mtrain definitions
name: Openscope_DendriticCoupling_v3

transitions:
  - trigger: progress
    source: PASSIVE_CLUSTER_HAB_10MIN_DAY6
    dest: PASSIVE_CLUSTER_HAB_20MIN_DAY7
    conditions: one_complete

  - trigger: progress
    source: PASSIVE_CLUSTER_HAB_20MIN_DAY7
    dest: PASSIVE_CLUSTER_HAB_30MIN_DAY8
    conditions: one_complete

  - trigger: progress
    source: PASSIVE_CLUSTER_HAB_30MIN_DAY8
    dest: PASSIVE_CLUSTER_HAB_40MIN_DAY9
    conditions: one_complete

  - trigger: progress
    source: PASSIVE_CLUSTER_HAB_40MIN_DAY9
    dest: PASSIVE_CLUSTER_HAB_50MIN_DAY10
    conditions: one_complete

  - trigger: manual
    source: PASSIVE_CLUSTER_HAB_50MIN_DAY10
    dest: PASSIVE_OPHYS_PROD_EXP_DAY11_15

  - trigger: manual
    source: PASSIVE_OPHYS_PROD_EXP_DAY11_15
    dest: PASSIVE_OPHYS_PROD_UNEXP_DAY16_18


stages:
  PASSIVE_CLUSTER_HAB_10MIN_DAY6:
    script: *pipeline_script
    script_md5: *pipeline_script_md5
    parameters:
      stage: PASSIVE_CLUSTER_HAB_10MIN_DAY6
      monitor_name: "Gamma1.Luminance50"
      type: 'hab'
      session_dur: 600
      pre_blank:  30
      post_blank: 30
      inter_blank:  30
      gab_dur:  135
      rot_gab_dur: 135
      sq_dur: 0
      movie_dur: 600
      movie_blocks: 3
      gratings_dur: 0
      movie_folder: //allen/programs/mindscope/workgroups/openscope/2022-DendriteCoupling/Scripts/Production/movies

  PASSIVE_CLUSTER_HAB_20MIN_DAY7:
    script: *pipeline_script
    script_md5: *pipeline_script_md5
    parameters:
      stage: PASSIVE_CLUSTER_HAB_20MIN_DAY7
      monitor_name: "Gamma1.Luminance50"
      type: 'hab'
      session_dur: 1200
      pre_blank:  30
      post_blank: 30
      inter_blank:  30
      gab_dur:  285
      rot_gab_dur: 285
      sq_dur: 0
      movie_dur: 600
      movie_blocks: 3
      gratings_dur: 0
      movie_folder: //allen/programs/mindscope/workgroups/openscope/2022-DendriteCoupling/Scripts/Production/movies

  PASSIVE_CLUSTER_HAB_30MIN_DAY8:
    script: *pipeline_script
    script_md5: *pipeline_script_md5
    parameters:
      stage: PASSIVE_CLUSTER_HAB_30MIN_DAY8
      monitor_name: "Gamma1.Luminance50"
      type: 'hab'
      session_dur: 1800
      pre_blank:  30
      post_blank: 30
      inter_blank:  30
      gab_dur:  435
      rot_gab_dur: 435
      sq_dur: 0
      movie_dur: 600
      movie_blocks: 3
      gratings_dur: 0
      movie_folder: //allen/programs/mindscope/workgroups/openscope/2022-DendriteCoupling/Scripts/Production/movies

  PASSIVE_CLUSTER_HAB_40MIN_DAY9:
    script: *pipeline_script
    script_md5: *pipeline_script_md5
    
    parameters:
      stage: PASSIVE_CLUSTER_HAB_40MIN_DAY9
      monitor_name: "Gamma1.Luminance50"
      type: 'hab'
      session_dur: 2400
      pre_blank:  30
      post_blank: 30
      inter_blank:  30
      gab_dur:  525
      rot_gab_dur: 525
      sq_dur: 0
      movie_dur: 600
      movie_blocks: 3
      gratings_dur: 0
      movie_folder: //allen/programs/mindscope/workgroups/openscope/2022-DendriteCoupling/Scripts/Production/movies

  PASSIVE_CLUSTER_HAB_50MIN_DAY10:
    script: *pipeline_script
    script_md5: *pipeline_script_md5

    parameters:
      stage: PASSIVE_CLUSTER_HAB_50MIN_DAY10
      monitor_name: "Gamma1.Luminance50"
      type: 'hab'
      session_dur: 3000
      pre_blank:  30
      post_blank: 30
      inter_blank:  30
      gab_dur:  735
      rot_gab_dur: 735
      sq_dur: 0
      movie_dur: 600
      movie_blocks: 3
      gratings_dur: 0
      movie_folder: //allen/programs/mindscope/workgroups/openscope/2022-DendriteCoupling/Scripts/Production/movies

  PASSIVE_OPHYS_PROD_EXP_DAY11_15:
    script: *pipeline_script
    script_md5: *pipeline_script_md5

    parameters:
      stage: PASSIVE_OPHYS_PROD_EXP_DAY11_15
      monitor_name: "Gamma1.Luminance50"
      type: 'hab'
      session_dur: 3600
      pre_blank:  30
      post_blank: 30
      inter_blank:  30
      gab_dur:  885
      rot_gab_dur: 885
      sq_dur: 0
      movie_dur: 600
      movie_blocks: 3
      gratings_dur: 0
      movie_folder: //allen/programs/mindscope/workgroups/openscope/2022-DendriteCoupling/Scripts/Production/movies

  PASSIVE_OPHYS_PROD_UNEXP_DAY16_18:
    script: *pipeline_script
    script_md5: *pipeline_script_md5

    parameters:
      stage: PASSIVE_OPHYS_PROD_UNEXP_DAY16_18
      monitor_name: "Gamma1.Luminance50"
      type: 'ophys'
      session_dur: 4200
      pre_blank:  30
      post_blank: 30
      inter_blank:  30
      gab_dur: 0 #1035
      rot_gab_dur: 0 #1035
      sq_dur: 0
      movie_dur: 600
      movie_blocks: 2
      gratings_dur: 0 
      movie_folder: //allen/programs/mindscope/workgroups/openscope/2022-DendriteCoupling/Scripts/Production/movies