_10min_cohort1_passive_training_cluster_script: &10min_cohort1_passive_training_cluster_script https://raw.githubusercontent.com/westerberg-science/openscope-glo-stim/a9bec00ccf599907c6520965f3f0379db18cc782/pilot-scripts/cohort-1/habituation/cohort-1-day-1-habituation-10min-drifting.py
_10min_cohort1_passive_training_cluster_script_md5: &10min_cohort1_passive_training_cluster_script_md5 f941f20cb3a31735e295520be719d783

_20min_cohort1_passive_training_cluster_script: &20min_cohort1_passive_training_cluster_script https://raw.githubusercontent.com/westerberg-science/openscope-glo-stim/a9bec00ccf599907c6520965f3f0379db18cc782/pilot-scripts/cohort-1/habituation/cohort-1-day-2-habituation-20min-drifting.py
_20min_cohort1_passive_training_cluster_script_md5: &20min_cohort1_passive_training_cluster_script_md5 be706559e398309d01e06599ddf4eadc

_30min_cohort1_passive_training_cluster_script: &30min_cohort1_passive_training_cluster_script https://raw.githubusercontent.com/westerberg-science/openscope-glo-stim/a9bec00ccf599907c6520965f3f0379db18cc782/pilot-scripts/cohort-1/habituation/cohort-1-day-3-habituation-30min-drifting.py
_30min_cohort1_passive_training_cluster_script_md5: &30min_cohort1_passive_training_cluster_script_md5 0cb5d9866ea25f0064d388350d00d36d

_40min_cohort1_passive_training_cluster_script: &40min_cohort1_passive_training_cluster_script https://raw.githubusercontent.com/westerberg-science/openscope-glo-stim/a9bec00ccf599907c6520965f3f0379db18cc782/pilot-scripts/cohort-1/habituation/cohort-1-day-4-habituation-40min-drifting.py
_40min_cohort1_passive_training_cluster_script_md5: &40min_cohort1_passive_training_cluster_script_md5 c171ca1fb7f4d53a8f52f0004c9629fd

_50min_cohort1_passive_training_cluster_script: &50min_cohort1_passive_training_cluster_script https://raw.githubusercontent.com/westerberg-science/openscope-glo-stim/a9bec00ccf599907c6520965f3f0379db18cc782/pilot-scripts/cohort-1/habituation/cohort-1-day-5-habituation-50min-drifting.py
_50min_cohort1_passive_training_cluster_script_md5: &50min_cohort1_passive_training_cluster_script_md5 ad747ca993124766b60a1b1167b88145

_60min_cohort1_passive_training_cluster_script: &60min_cohort1_passive_training_cluster_script https://raw.githubusercontent.com/westerberg-science/openscope-glo-stim/a9bec00ccf599907c6520965f3f0379db18cc782/pilot-scripts/cohort-1/habituation/cohort-1-day-6,7-habituation-60min-drifting.py
_60min_cohort1_passive_training_cluster_script_md5: &60min_cohort1_passive_training_cluster_script_md5 c0927a81caeaa05fc2117968c02a3da2

_90min_cohort1_passive_training_cluster_script: &90min_cohort1_passive_training_cluster_script https://raw.githubusercontent.com/westerberg-science/openscope-glo-stim/a9bec00ccf599907c6520965f3f0379db18cc782/pilot-scripts/cohort-1/habituation/cohort-1-day-8,9-habituation-90min-drifting.py
_90min_cohort1_passive_training_cluster_script_md5: &90min_cohort1_passive_training_cluster_script_md5 75fc1dd5024d0ed3aef124d7f82a651c

_120min_cohort1_passive_training_cluster_script: &120min_cohort1_passive_training_cluster_script https://raw.githubusercontent.com/westerberg-science/openscope-glo-stim/a9bec00ccf599907c6520965f3f0379db18cc782/pilot-scripts/cohort-1/habituation/cohort-1-day-10-habituation-120min-drifting.py
_120min_cohort1_passive_training_cluster_script_md5: &120min_cohort1_passive_training_cluster_script_md5 641da3e4fe792d566f52e141fffc64e3

_120min_cohort1_passive_prod_ephys_script: &120min_cohort1_passive_prod_ephys_script https://raw.githubusercontent.com/westerberg-science/openscope-glo-stim/ef5f1f69fd364f1e63f843c09f7aa1d0cddfd912/pilot-scripts/cohort-1/ephysrecording/cohort-1-day-11-ephysrecording-120min-drifting.py
_120min_cohort1_passive_prod_ephys_script_md5: &120min_cohort1_passive_prod_ephys_script_md5 ca61eb586dfa59fc3b5fe1047790db7c


### mtrain definitions
name: Openscope_GlobalLocalOdd_Cohort1_v1.0.5

transitions:
  - trigger: progress
    source: PASSIVE_CLUSTER_HAB_10MIN_DAY6
    dest: PASSIVE_CLUSTER_HAB_20MIN_DAY7
    conditions: one_complete

  - trigger: progress
    source: PASSIVE_CLUSTER_HAB_20MIN_DAY7
    dest: PASSIVE_CLUSTER_HAB_30MIN_DAY8
    conditions: one_complete

  - trigger: progress
    source: PASSIVE_CLUSTER_HAB_30MIN_DAY8
    dest: PASSIVE_CLUSTER_HAB_40MIN_DAY9
    conditions: one_complete

  - trigger: progress
    source: PASSIVE_CLUSTER_HAB_40MIN_DAY9
    dest: PASSIVE_CLUSTER_HAB_50MIN_DAY10
    conditions: one_complete
  
  - trigger: manual
    source: PASSIVE_CLUSTER_HAB_50MIN_DAY10
    dest: PASSIVE_EPHYS_HAB_60MIN_DAY1_2

  - trigger: manual
    source: PASSIVE_EPHYS_HAB_60MIN_DAY1_2
    dest: PASSIVE_EPHYS_HAB_90MIN_DAY3_4

  - trigger: manual
    source: PASSIVE_EPHYS_HAB_90MIN_DAY3_4
    dest: PASSIVE_EPHYS_HAB_120MIN_DAY5

  - trigger: manual
    source: PASSIVE_EPHYS_HAB_120MIN_DAY5
    dest: PASSIVE_EPHYS_PROD_120MIN_DAY1

stages:
  PASSIVE_CLUSTER_HAB_10MIN_DAY6:
    script: *10min_cohort1_passive_training_cluster_script
    script_md5: *10min_cohort1_passive_training_cluster_script_md5
    parameters:
      stage: PASSIVE_CLUSTER_HAB_10MIN_DAY6

      # control number of repetition to make longer script
      n_rep: 2

  PASSIVE_CLUSTER_HAB_20MIN_DAY7:
    script: *20min_cohort1_passive_training_cluster_script
    script_md5: *20min_cohort1_passive_training_cluster_script_md5
    parameters:
      stage: PASSIVE_CLUSTER_HAB_20MIN_DAY7

      # control number of repetition to make longer script
      n_rep: 5

  PASSIVE_CLUSTER_HAB_30MIN_DAY8:
    script: *30min_cohort1_passive_training_cluster_script
    script_md5: *30min_cohort1_passive_training_cluster_script_md5
    parameters:
      stage: PASSIVE_CLUSTER_HAB_30MIN_DAY8

      # control number of repetition to make longer script
      n_rep: 8

  PASSIVE_CLUSTER_HAB_40MIN_DAY9:
    script: *40min_cohort1_passive_training_cluster_script
    script_md5: *40min_cohort1_passive_training_cluster_script_md5
    
    parameters:
      stage: PASSIVE_CLUSTER_HAB_40MIN_DAY9

      # control number of repetition to make longer script
      n_rep: 10

  PASSIVE_CLUSTER_HAB_50MIN_DAY10:
    script: *50min_cohort1_passive_training_cluster_script
    script_md5: *50min_cohort1_passive_training_cluster_script_md5

    parameters:
      stage: PASSIVE_CLUSTER_HAB_50MIN_DAY10

      # control number of repetition to make longer script
      n_rep: 14

  PASSIVE_EPHYS_HAB_60MIN_DAY1_2:
    script: *60min_cohort1_passive_training_cluster_script
    script_md5: *60min_cohort1_passive_training_cluster_script_md5

    parameters:
      stage: PASSIVE_EPHYS_HAB_60MIN_DAY1_2

      # control number of repetition to make longer script
      durfac: 2

  PASSIVE_EPHYS_HAB_90MIN_DAY3_4:
    script: *90min_cohort1_passive_training_cluster_script
    script_md5: *90min_cohort1_passive_training_cluster_script_md5

    parameters:
      stage: PASSIVE_EPHYS_HAB_90MIN_DAY3_4

      # control number of repetition to make longer script
      durfac: 3
      
  PASSIVE_EPHYS_HAB_120MIN_DAY5:
    script: *120min_cohort1_passive_training_cluster_script
    script_md5: *120min_cohort1_passive_training_cluster_script_md5

    parameters:
      stage: PASSIVE_EPHYS_HAB_120MIN_DAY5

      # no optotagging
      opto: false
      
  PASSIVE_EPHYS_PROD_120MIN_DAY1:
    script: *120min_cohort1_passive_prod_ephys_script
    script_md5: *120min_cohort1_passive_prod_ephys_script_md5

    parameters:
      stage: PASSIVE_EPHYS_PROD_120MIN_DAY1

      # optotagging
      opto: true