_script_0: &script_0 http://stash.corp.alleninstitute.org/users/sams/repos/visual_behavior_scripts/raw/vip_stabilized_network/Phase_4_VIP_day0/SparseNoise_day0.py?at=b0b070e2521247cbd178ecd70bbd42b65c397fd6

_script_0_md5: &script_0_md5 676f99bef36d899c6aa276ca601c59d7

_script_1: &script_1 http://stash.corp.alleninstitute.org/users/sams/repos/visual_behavior_scripts/raw/vip_stabilized_network/Phase_4_VIP_day1to9/SizeByContrast_day1to9.py?at=f0bfcf80984f2730b2d7da0f3c176291a1aa2697

_script_1_md5: &script_1_md5 be10677a4553e5acaf415eb308995407

### mtrain definitions
#based on VisualBehavior_Task1A_v1.0.3
name: VisualCoding_VipSsn_v1.0.9

transitions:
  - trigger: manual
    source: STAGE_0
    dest: STAGE_1

stages:
  STAGE_0:
    script: *script_0
    script_md5: *script_0_md5
    parameters:
      stage: STAGE_0
  STAGE_1:
    script: *script_1
    script_md5: *script_1_md5
    parameters:
      stage: STAGE_1