_resource_id: &resource_id bcd1d5d18f28dbc7df17b0eabfa2c2759de52d1c

_gratings_stimulus: &gratings_stimulus
  class: gratings
  params:
    sf: 0.04
    size: [200, 150]
    units: deg
    tex: sqr
  groups:
    group_0:
      Ori: [90]
      phase: [0.25]
    group_1:
      Ori: [180]
      phase: [0.25]

_parameters: &parameters
  dev: false
  monitor: "Gamma1.Luminance50" 
  auto_reward_delay: 0.6 
  auto_reward_vol: 0.005 
  catch_frequency: 0.0 
  change_flashes_max: null 
  change_flashes_min: null 
  periodic_flash: null 
  change_time_dist: exponential
  change_time_scale: 2.0
  pre_change_time: 18.0
  stimulus_window: 6.0
  end_after_response: true
  end_after_response_sec: 0.0
  failure_repeats: 0
  free_reward_trials: 1
  max_task_duration_min: 60.0
  start_stop_padding: 1
  max_trials: 2000
  min_no_lick_time: 0.0
  response_window: [0.15, 1.0]
  reward_volume: 0.0
  volume_limit: 5.0
  warm_up_trials: 1
  explicit_monitor: "Gamma1.Luminance50"
  allow_contiguous_holds: false
  auto_reward_hold_freq: 0.2
  consumption_window: null

### mtrain definitions
name: AssociativeLearning_Static_dev2

transitions:
  # in case a transition is required by mtrain
  - trigger: manual
    source: STAGE_0
    dest: STAGE_1

stages:
  STAGE_0:
    script_md5: associative-script-v1.py
    script: associative-script-v1.py
    parameters:
      <<: *parameters
      stage: STAGE_0
      stimulus: *gratings_stimulus
  STAGE_1:
    script_md5: associative-script-v1.py
    script: associative-script-v1.py
    parameters:
      <<: *parameters
      stage: STAGE_1
      stimulus: *gratings_stimulus
