_resource_id: &resource_id bf8441cfa18d67accc173f72231989ae342091e9

_gratings_stimulus: &gratings_stimulus
  class: gratings
  params:
    SF: [0.04]
    size: [200, 150]
    units: deg
  groups:
    group_0:
      Ori: [90]
      phase: [0.25]
    group_1:
      Ori: [180]
      phase: [0.25]

_parameters: &parameters
  monitor: testMonitor
  auto_reward_delay: 0.6
  auto_reward_vol: 0.007
  catch_frequency: null
  change_flashes_max: 12
  change_flashes_min: 4
  change_time_dist: geometric
  change_time_scale: 0.3
  end_after_response: true
  end_after_response_sec: 0.0
  failure_repeats: 5
  flash_omit_probability: 1.0
  free_reward_trials: 1
  max_task_duration_min: 60.0
  max_trials: 2000
  min_no_lick_time: 0.0
  periodic_flash: [0.25, 0.5]
  pre_change_time: 0.0
  response_window: [0.15, 0.75]
  reward_volume: 0.007
  start_stop_padding: 5.0
  stimulus_window": 6.0
  task_id: DoC
  timeout_duration: 0.3
  volume_limit: 5.0
  warm_up_trials: 1
  explicit_monitor: testMonitor
  previous_consumption_change_flash_extension: 5.0
  allow_contiguous_holds: false
  auto_reward_hold_freq: 0.2
  consumption_window: null

### mtrain definitions
name: AssociativeLearning_v0.0.1

transitions:
  # in case a transition is required by mtrain
  - trigger: manual
    source: STAGE_0
    dest: STAGE_1

stages:
  STAGE_0:
    script: *resource_id
    script_md5: *resource_id # v2 compatability?
    parameters:
      <<: *parameters
      stage: STAGE_0
      stimulus: *gratings_stimulus
  STAGE_1:
    script: *resource_id
    script_md5: *resource_id # v2 compatability?
    parameters:
      <<: *parameters
      stage: STAGE_1
      stimulus: *gratings_stimulus
