_script_0: &script_0 http://stash.corp.alleninstitute.org/projects/VB/repos/visual_behavior_scripts/raw/testing/TenSessionClips_0.py?at=500697e44ba5b7237ed7afc7cec069746f50892a

_script_0_md5: &script_0_md5 5f042b8ab04d6106d86d3d4fdcee5dc3


### mtrain definitions
name: V1omFISH_gamma_v1.1.0

transitions:
  - trigger: manual
    source: 40hz
    dest: 40hz_random

  - trigger: manual
    source: 40hz_random
    dest: square_stim

  - trigger: manual
    source: square_stim
    dest: 8hz

stages:
  40hz:
    script: *script_0
    script_md5: *script_0_md5
    parameters:
      stage: 40hz
  40hz_random:
    script: *script_0
    script_md5: *script_0_md5
    parameters:
      stage: 40hz_random
  square_stim:
    script: *script_0
    script_md5: *script_0_md5
    parameters:
      stage: square_stim
  8hz:
    script: *script_0
    script_md5: *script_0_md5
    parameters:
      stage: 8hz