_script: &script dynamic_routing.py
_script_md5: &script_md5 dynamic_routing.py
_parameters: &parameters
  mtrain_translator: "dynamic_routing"
  taskScript: //allen/programs/mindscope/workgroups/dynamicrouting/DynamicRoutingTask/DynamicRouting1.py
### mtrain definitions
name: DynamicRoutingAlternating_1_v0.0.0
transitions:
  - trigger: progress
    source: STAGE_5_ORI_AMN_MOVING_NOAR
    dest: STAGE_5_AMN_ORI_MOVING_NOAR
  - trigger: progress
    source: STAGE_5_AMN_ORI_MOVING_NOAR
    dest: STAGE_5_ORI_AMN_MOVING_NOAR
stages:
  STAGE_5_ORI_AMN_MOVING_NOAR:
    script: *script
    script_md5: *script_md5
    parameters:
      <<: *parameters
      stage: STAGE_5_ORI_AMN_MOVING_NOAR
      taskVersion: "stage 5 ori AMN moving noAR"
  STAGE_5_AMN_ORI_MOVING_NOAR:
    script: *script
    script_md5: *script_md5
    parameters:
      <<: *parameters
      stage: STAGE_5_AMN_ORI_MOVING_NOAR
      taskVersion: "stage 5 AMN ori moving noAR"
