_change_detection_script: &change_detection_script http://stash.corp.alleninstitute.org/projects/VB/repos/visual_behavior_scripts/raw/change_detection_extended.py?at=07db49c7b1336663be281a93677118b1f3e29ee1

_change_detection_script_md5: &change_detection_script_md5 08e339fd1af048c928665c9f31ef434c

_movie_clips_script: &movie_clips_script http://stash.corp.alleninstitute.org/projects/VB/repos/visual_behavior_scripts/raw/receptive_field_mapping.py?at=46ae5481552b2ab22ffa580260426399ae40ffba

_movie_clips_script_md5: &movie_clips_script_md5 8cab71e3cf5acdeef9a4660b09e52798

_replay_script: &replay_script http://stash.corp.alleninstitute.org/projects/VB/repos/visual_behavior_scripts/raw/replay_script.py?at=cc7f17850dadce0f5f225419d639bda5732fc76e

_replay_script_md5: &replay_script_md5 815b692de909ace7b49a8a1cfe8eec38

_full_field_gratings_stimulus: &full_field_gratings
  class: grating
  params:
    sf: 0.04
    tex: sqr
    size: [200, 150]
    units: deg
    phase: 0.25
  groups:
    vertical:
      Ori: [0, 180]
    horizontal:
      Ori: [90, 270]

_image_set_g_stimulus: &image_set_g
  class: images
  params:
    image_set: //allen/programs/braintv/workgroups/nc-ophys/visual_behavior/image_dictionaries/Natural_Images_Lum_Matched_set_ophys_G_2019.05.26.pkl
    sampling: even

_image_set_h_stimulus: &image_set_h
  class: images
  params:
    image_set: //allen/programs/braintv/workgroups/nc-ophys/visual_behavior/image_dictionaries/Natural_Images_Lum_Matched_set_ophys_H_2019.05.26.pkl
    sampling: even

_mapping_movie_list: &mapping_movie_list
  - name: gabor
    params:
      frame_length: 0.016666666666666666
      movie_path: //allen/programs/braintv/workgroups/nc-ophys/1022/mapping_stim_movies/gabor-remastered-1576117355.npy
      runs: 5 # 1 min each run
      size: [1920, 1080]

  - name: flash
    params:
      frame_length: 0.016666666666666666
      movie_path: //allen/programs/braintv/workgroups/nc-ophys/1022/mapping_stim_movies/flash-remastered-1576272856.npy
      runs: 5 # 1 min each
      size: [1920, 1080]

_flash_parameters: &flash_parameters
  task_id: DoC

  catch_frequency: 0.25
  failure_repeats: 5

  # rewards (mL)
  reward_volume: 0.007
  volume_limit: 5.0

  # auto rewards
  auto_reward_vol: 0.005
  warm_up_trials: 5
  auto_reward_delay: 0.150
  free_reward_trials: 10000

  # trial timing
  min_no_lick_time: 0.0
  timeout_duration: 0.3
  pre_change_time: 0.0
  stimulus_window: 6.0
  max_task_duration_min: 60.0
  periodic_flash: [0.25, 0.5]
  response_window: [0.15, 0.75]
  end_after_response: True
  end_after_response_sec: 3.5

  # timing of changes
  change_time_dist: geometric
  change_time_scale: 0.3
  change_flashes_min: 4 # inclusive
  change_flashes_max: 12 # exclusive

_no_flash_parameters: &no_flash_parameters
  <<: *flash_parameters
  periodic_flash: null
  response_window: [0.15, 1.0]
  reward_volume: 0.010
  free_reward_trials: 10
  pre_change_time: 2.25

  # timing of changes
  change_time_dist: exponential
  change_time_scale: 2.0
  change_flashes_min: null
  change_flashes_max: null

_image_set_g_parameters: &image_set_g_parameters
  <<: *flash_parameters
  stimulus: *image_set_g
  catch_frequency: null

_image_set_h_parameters: &image_set_h_parameters
  <<: *flash_parameters
  stimulus: *image_set_h
  catch_frequency: null

_replay_g_parameters: &replay_g_parameters
  <<: *flash_parameters
  stimulus: *image_set_g
  catch_frequency: null
  mapping:
    flash_path: //allen/programs/braintv/workgroups/nc-ophys/1022/replay-stim/flash_250ms.stim
    gabor_path: //allen/programs/braintv/workgroups/nc-ophys/1022/replay-stim/gabor_20_deg_250ms.stim
  output_dir: C:/ProgramData/camstim/output
  agent_socket: "127.0.0.1:5000"

_replay_h_parameters: &replay_h_parameters
  <<: *flash_parameters
  stimulus: *image_set_h
  catch_frequency: null
  mapping:
    flash_path: //allen/programs/braintv/workgroups/nc-ophys/1022/replay-stim/flash_250ms.stim
    gabor_path: //allen/programs/braintv/workgroups/nc-ophys/1022/replay-stim/gabor_20_deg_250ms.stim
  output_dir: C:/ProgramData/camstim/output
  agent_socket: "127.0.0.1:5000"

### mtrain definitions
#based on VisualBehavior_Task1A_v1.0.3
name: VisualBehaviorEPHYS_Task2A_v0.0.1

transitions:
  - trigger: progress
    source: TRAINING_0_gratings_autorewards_15min
    dest: TRAINING_1_gratings
    conditions: one_complete

  - trigger: progress
    source: TRAINING_1_gratings
    dest: TRAINING_2_gratings_flashed
    conditions: [two_out_of_three_aint_bad, yesterday_was_good]

  - trigger: progress
    source: TRAINING_2_gratings_flashed
    dest: TRAINING_3_images_G_10uL_reward
    conditions: [two_out_of_three_aint_bad, yesterday_was_good]

  - trigger: progress
    source: TRAINING_3_images_G_10uL_reward
    dest: TRAINING_4_images_G_training
    conditions: three_complete

  - trigger: progress
    source: TRAINING_4_images_G_training
    dest: TRAINING_5_images_G_epilogue
    conditions: meets_engagement_criteria

  - trigger: progress
    source: TRAINING_5_images_G_epilogue
    dest: TRAINING_5_images_G_handoff_ready
    conditions: meets_engagement_criteria

  - trigger: progress
    source: TRAINING_5_images_G_handoff_ready
    dest: TRAINING_5_images_G_handoff_lapsed
    unless: meets_engagement_criteria

  - trigger: progress
    source: TRAINING_5_images_G_handoff_lapsed
    dest: TRAINING_5_images_G_handoff_ready
    conditions: meets_engagement_criteria

  - trigger: manual
    source: TRAINING_5_images_G_handoff_ready
    dest: HABITUATION_5_images_G_handoff_ready

  - trigger: manual
    source: HABITUATION_5_images_G_handoff_ready
    dest: EPHYS_1_images_G_5uL_reward

  - trigger: manual
    source: EPHYS_1_images_G_5uL_reward
    dest: EPHYS_1_images_H_5uL_reward

stages:
  TRAINING_0_gratings_autorewards_15min:
    script: *change_detection_script
    script_md5: *change_detection_script_md5
    parameters:
      <<: *no_flash_parameters
      stage: TRAINING_0_gratings_autorewards_15min
      stimulus: *full_field_gratings

      # auto rewards
      warm_up_trials: -1 #infinite
      abort_on_early_response: False
      catch_frequency: 0.0

      response_window: [0.0, 0.0]
      min_no_lick_time: 0.0
      failure_repeats: 0

      # trial timing
      max_task_duration_min: 15.0

      # rewards (mL)
      reward_volume: 0.0

      # ephys-specific no grayscreen pre-exp time
      start_padding_windowless: 20.0

  TRAINING_1_gratings:
    script: *change_detection_script
    script_md5: *change_detection_script_md5
    parameters:
      <<: *no_flash_parameters
      stage: TRAINING_1_gratings

      stimulus: *full_field_gratings

      # ephys-specific no grayscreen pre-exp time
      start_padding_windowless: 20.0

  TRAINING_2_gratings_flashed:
    script: *change_detection_script
    script_md5: *change_detection_script_md5
    parameters:
      <<: *flash_parameters
      stage: TRAINING_2_gratings_flashed
      task_id: DoC

      stimulus: *full_field_gratings
      free_reward_trials: 10

      # rewards (mL)
      reward_volume: 0.01

      # ephys-specific no grayscreen pre-exp time
      start_padding_windowless: 20.0

  TRAINING_3_images_G_10uL_reward:
    script: *change_detection_script
    script_md5: *change_detection_script_md5
    parameters:
      <<: *image_set_g_parameters
      stage: TRAINING_3_images_G_10uL_reward

      # rewards (mL)
      reward_volume: 0.01
      free_reward_trials: 10

      # ephys-specific no grayscreen pre-exp time
      start_padding_windowless: 20.0

  TRAINING_4_images_G_training:
    script: *change_detection_script
    script_md5: *change_detection_script_md5
    parameters:
      <<: *image_set_g_parameters
      stage: TRAINING_4_images_G_training

      # ephys-specific no grayscreen pre-exp time
      start_padding_windowless: 20.0

  TRAINING_5_images_G_epilogue:
    script: *change_detection_script
    script_md5: *change_detection_script_md5
    parameters:
      <<: *image_set_g_parameters
      stage: TRAINING_5_images_G_epilogue
      warm_up_trials: 5
      reward_volume: 0.005

      # ephys-specific no grayscreen pre-exp time
      start_padding_windowless: 300.0

      # play list of movies mimicking a mapping session
      epilogue_list: *mapping_movie_list

  TRAINING_5_images_G_handoff_ready:
    script: *change_detection_script
    script_md5: *change_detection_script_md5
    parameters:
      <<: *image_set_g_parameters
      stage: TRAINING_5_images_G_handoff_ready
      warm_up_trials: 5
      reward_volume: 0.005

      # ephys-specific no grayscreen pre-exp time
      start_padding_windowless: 300.0

      # play list of movies mimicking a mapping session
      epilogue_list: *mapping_movie_list

  TRAINING_5_images_G_handoff_lapsed:
    script: *change_detection_script
    script_md5: *change_detection_script_md5
    parameters:
      <<: *image_set_g_parameters
      stage: TRAINING_5_images_G_handoff_lapsed
      warm_up_trials: 5
      reward_volume: 0.005

      # ephys-specific no grayscreen pre-exp time
      start_padding_windowless: 300.0

      # play list of movies mimicking a mapping session
      epilogue_list: *mapping_movie_list

  HABITUATION_5_images_G_handoff_ready:
    script: *change_detection_script
    script_md5: *change_detection_script_md5
    parameters:
      <<: *image_set_g_parameters
      stage: HABITUATION_TRAINING_5_images_G_handoff_ready
      warm_up_trials: 5
      reward_volume: 0.005

      # ephys-specific no grayscreen pre-exp time
      start_padding_windowless: 20.0
      # play list of movies mimicking a mapping session
      epilogue_list: *mapping_movie_list

  EPHYS_1_images_G_5uL_reward:
    script: *replay_script
    script_md5: *replay_script_md5
    parameters:
      <<: *replay_g_parameters
      stage: EPHYS_1_images_G_5uL_reward
      warm_up_trials: 3
      flash_omit_probability: 0.05
      reward_volume: 0.005

  EPHYS_1_images_H_5uL_reward:
    script: *replay_script
    script_md5: *replay_script_md5
    parameters:
      <<: *replay_h_parameters
      stage: EPHYS_1_images_H_5uL_reward
      warm_up_trials: 3
      flash_omit_probability: 0.05
      reward_volume: 0.005
