_script: &script dynamic_routing.py
_script_md5: &script_md5 dynamic_routing.py # same if script is a resource id
_parameters: &parameters
  mtrain_translator: "dynamic_routing"
### mtrain definitions
name: DynamicRoutingDev_v0.0.0
transitions:
  - trigger: progress
    source: STAGE_0.0
    dest: STAGE_0.1
  - trigger: progress
    source: STAGE_0.1
    dest: STAGE_0.2
    conditions: v2_dynamic_routing_meets_hit_count_and_dprime_same_modal
    unless: v2_dynamic_routing_fails_minimum_hit_count
  - trigger: progress
    source: STAGE_0.1
    dest: STAGE_0.0
    conditions: v2_dynamic_routing_fails_minimum_hit_count
  - trigger: progress
    source: STAGE_0.2
    dest: STAGE_0.3_ORI_AMN
    conditions: v2_dynamic_routing_meets_dprime_same_modal_and_dprime_other_modal
  - trigger: progress
    source: STAGE_0.3_ORI_AMN
    dest: STAGE_0.3_AMN_ORI
    unless: v2_dynamic_routing_meets_dprime_same_modal_and_dprime_other_modal_state_agnostic
  - trigger: progress
    source: STAGE_0.3_AMN_ORI
    dest: STAGE_0.3_ORI_AMN
    unless: v2_dynamic_routing_meets_dprime_same_modal_and_dprime_other_modal_state_agnostic
  - trigger: progress
    source: STAGE_0.3_ORI_AMN
    dest: STAGE_0.4_ORI_AMN
    conditions: v2_dynamic_routing_meets_dprime_same_modal_and_dprime_other_modal_state_agnostic
  - trigger: progress
    source: STAGE_0.3_AMN_ORI
    dest: STAGE_0.4_AMN_ORI
    conditions: v2_dynamic_routing_meets_dprime_same_modal_and_dprime_other_modal_state_agnostic
  - trigger: progress
    source: STAGE_0.4_AMN_ORI
    dest: STAGE_0.4_ORI_AMN
  - trigger: progress
    source: STAGE_0.4_ORI_AMN
    dest: STAGE_0.4_AMN_ORI
  - trigger: manual
    source: STAGE_0.4_AMN_ORI
    dest: STAGE_0.5_AMN_ORI
  - trigger: manual
    source: STAGE_0.4_ORI_AMN
    dest: STAGE_0.5_ORI_AMN
stages:
  STAGE_0.0:
    script: *script
    script_md5: *script_md5
    parameters:
      <<: *parameters
      stage: STAGE_0.0
      taskVersion: "stage 0 moving"
  STAGE_0.1:
    script: *script
    script_md5: *script_md5
    parameters:
      <<: *parameters
      stage: STAGE_0.1
      taskVersion: "stage 1 AMN moving timeouts"
  STAGE_0.2:
    script: *script
    script_md5: *script_md5
    parameters:
      <<: *parameters
      stage: STAGE_0.2
      taskVersion: "stage 2 AMN timeouts"
  STAGE_0.3_ORI_AMN:
    script: *script
    script_md5: *script_md5
    parameters:
      <<: *parameters
      stage: STAGE_0.3_ORI_AMN
      taskVersion: "stage 5 ori AMN moving timeouts"
  STAGE_0.3_AMN_ORI:
    script: *script
    script_md5: *script_md5
    parameters:
      <<: *parameters
      stage: STAGE_0.3_AMN_ORI
      taskVersion: "stage 5 AMN ori moving timeouts"
  STAGE_0.4_ORI_AMN:
    script: *script
    script_md5: *script_md5
    parameters:
      <<: *parameters
      stage: STAGE_0.4_ORI_AMN
      taskVersion: "stage 5 ori AMN moving"
  STAGE_0.4_AMN_ORI:
    script: *script
    script_md5: *script_md5
    parameters:
      <<: *parameters
      stage: STAGE_0.4_AMN_ORI
      taskVersion: "stage 5 AMN ori moving"
  STAGE_0.5_ORI_AMN:
    script: *script
    script_md5: *script_md5
    parameters:
      <<: *parameters
      stage: STAGE_0.5_ORI_AMN
      taskVersion: "stage 5 ori AMN moving"
  STAGE_0.5_AMN_ORI:
    script: *script
    script_md5: *script_md5
    parameters:
      <<: *parameters
      stage: STAGE_0.5_AMN_ORI
      taskVersion: "stage 5 AMN ori moving"
