name: v0.1.3
transitions:

  - trigger: progress
    source: 1_AutoRewards
    dest: static_full_field_gratings
    conditions: autorewards_complete

  - trigger: progress
    source: static_full_field_gratings
    dest: static_full_field_gratings_flash_500ms
    conditions: [two_out_of_three_aint_bad, yesterday_was_good]

  - trigger: progress
    source: static_full_field_gratings_flash_500ms
    dest: natural_images
    conditions: [two_out_of_three_aint_bad, yesterday_was_good]

  - trigger: progress
    source: natural_images
    dest: natural_images_drop_reward
    conditions: three_complete

  - trigger: progress
    source: natural_images_drop_reward
    dest: ready_for_imaging
    conditions: meets_engagement_criteria

  - trigger: progress
    source: ready_for_imaging
    dest: not_ready_for_imaging
    unless: meets_engagement_criteria

  - trigger: progress
    source: not_ready_for_imaging
    dest: ready_for_imaging
    conditions: meets_engagement_criteria

  - trigger: handoff
    source: ready_for_imaging
    dest: ophys_set_a
    conditions: meets_engagement_criteria

  - trigger: progress
    source: ophys_set_a
    dest: ophys_set_a_passive
    conditions: four_complete

  - trigger: progress
    source: ophys_set_a_passive
    dest: ophys_set_c
    conditions: one_complete

  - trigger: progress
    source: ophys_set_c
    dest: ophys_set_c_passive
    conditions: four_complete

  - trigger: progress
    source: ophys_set_c_passive
    dest: receptive_field_mapping
    conditions: one_complete

stages:

    1_AutoRewards:
        script: *change_detection_script
        script_md5: *change_detection_script_md5
        parameters:

            stage: 1_AutoRewards
            task_id: DoC

            stimulus: *full_field_gratings

            # rewards (ml)
            auto_reward_vol: 0.005 # in microliters
            volume_limit: 1.5

            # auto rewards
            warm_up_trials: -1 #infinite
            auto_reward_vol: 0.005 # in microliters
            abort_on_early_response: False
            auto_reward_delay: 0.150

            # trial timing
            periodic_flash: None
            initial_blank: 0
            pre_change_time: 2.25
            stimulus_window: 6.0
            max_task_duration_min: 15.0
            start_stop_padding: 10.0


    static_full_field_gratings:
        script: *change_detection_script
        script_md5: *change_detection_script_md5
        parameters:
            stage: static_full_field_gratings
            task_id: DoC

            stimulus: *full_field_gratings

            catch_frequency: 0.25
            failure_repeats: 5

            # rewards (mL)
            auto_reward_vol: 0.005
            reward_vol: 0.01
            volume_limit: 5.0

            # auto rewards
            auto_reward_vol: 0.005
            warm_up_trials: 5
            auto_reward_delay: 0.150

            # trial timing
            periodic_flash: None
            pre_change_time: 2.25
            stimulus_window: 6.0
            response_window: [0.15,1.0]
            max_task_duration_min: 60.0
            start_stop_padding: 10.0


    static_full_field_gratings_flash_500ms:
        script: *change_detection_script
        script_md5: *change_detection_script_md5
        parameters:
            stage: static_full_field_gratings_flash_500ms
            task_id: DoC

            stimulus: *full_field_gratings

            catch_frequency: 0.25
            failure_repeats: 5

            # rewards (mL)
            auto_reward_vol: 0.005
            reward_vol: 0.01
            volume_limit: 5.0

            # auto rewards
            auto_reward_vol: 0.005
            warm_up_trials: 5
            auto_reward_delay: 0.150

            # trial timing
            periodic_flash: [0.25, 0.5]
            pre_change_time: 2.25
            stimulus_window: 6.0
            response_window: [0.15,0.75]
            max_task_duration_min: 60.0
            start_stop_padding: 10.0


    natural_images:
        script: *change_detection_script
        script_md5: *change_detection_script_md5
        parameters:
            <<: *image_set_a_parameters
            stage: natural_images
            task_id: DoC

            catch_frequency: 0.125
            failure_repeats: 5

            # rewards (mL)
            auto_reward_vol: 0.005
            reward_vol: 0.01

    natural_images_drop_reward:
        script: *change_detection_script
        script_md5: *change_detection_script_md5
        parameters:
            <<: *image_set_a_parameters
            stage: natural_images_drop_reward

            catch_frequency: 0.125
            failure_repeats: 5

            # rewards (mL)
            auto_reward_vol: 0.005
            reward_vol: 0.007
            volume_limit: 5.0

            # auto rewards
            warm_up_trials: 5

            # trial timing
            periodic_flash: [0.25, 0.5]
            pre_change_time: 2.25
            stimulus_window: 6.0
            response_window: [0.15,0.75]
            max_task_duration_min: 60.0

            trial_translator: True

    ready_for_imaging:
        script: *change_detection_script
        script_md5: *change_detection_script_md5
        parameters:
            <<: *image_set_a_parameters
            stage: ready_for_imaging

            catch_frequency: 0.125
            failure_repeats: 5

            # rewards (mL)
            auto_reward_vol: 0.005
            reward_vol: 0.007
            volume_limit: 5.0

            # auto rewards
            warm_up_trials: 5

            # trial timing
            periodic_flash: [0.25, 0.5]
            pre_change_time: 2.25
            stimulus_window: 6.0
            response_window: [0.15,0.75]
            max_task_duration_min: 60.0

            trial_translator: True

    not_ready_for_imaging:
        script: *change_detection_script
        script_md5: *change_detection_script_md5
        parameters:
            <<: *image_set_a_parameters
            stage: not_ready_for_imaging

    ophys_set_a:
        script: *change_detection_script
        script_md5: *change_detection_script_md5
        parameters:
            <<: *image_set_a_parameters
            stage: ophys_set_a

            # rewards (mL)
            auto_reward_vol: 0.005
            reward_vol: 0.007
            volume_limit: 5.0

    ophys_set_c:
        script: *change_detection_script
        script_md5: *change_detection_script_md5
        parameters:
            <<: *image_set_c_parameters
            stage: ophys_set_c

    ophys_set_c_passive:
        script: *change_detection_script
        script_md5: *change_detection_script_md5
        parameters:
            <<: *image_set_c_parameters
            stage: ophys_set_c_passive
            lick_spout: False

    receptive_field_mapping:
        script: *movie_clips_script
        script_md5: *movie_clips_script_md5
        parameters:
            stage: receptive_field_mapping
