_change_detection_script: &change_detection_script http://stash.corp.alleninstitute.org/projects/VB/repos/visual_behavior_scripts/raw/change_detection_with_fingerprint.py?at=021ec55fbbdbb05aad1681c016e83066fe5aa1dd

_change_detection_script_md5: &change_detection_script_md5 e0535f3b6f03ccc8eeccaed2118f3c1d

_movie_clips_script: &movie_clips_script http://stash.corp.alleninstitute.org/users/chrism/repos/aibs-scripts-stash/raw/scripts/script_7/script.py?at=ff7e555d5849786de1ab0c84471bd9f30df7ba64

_movie_clips_script_md5: &movie_clips_script_md5 c71e4b49a38542f21ea1053fd0c17920

_replay_script: &replay_script http://stash.corp.alleninstitute.org/users/chrism/repos/aibs-scripts-stash/raw/scripts/replay_script/script.py?at=ff2495ae48d1c7fad57fb13f686cf4028fd5729a

_replay_script_md5: &replay_script_md5 bc07124394869a9d6506efd412044c5c

_full_field_gratings_stimulus: &full_field_gratings
  class: grating
  params:
    sf: 0.04
    tex: sqr
    size: [200, 150]
    units: deg
    phase: 0.25
  groups:
    vertical:
      Ori: [0, 180]
    horizontal:
      Ori: [90, 270]

_image_set_a_stimulus: &image_set_a
  class: images
  params:
    image_set: //allen/programs/braintv/workgroups/nc-ophys/visual_behavior/image_dictionaries/Natural_Images_Lum_Matched_set_training_2017.07.14.pkl
    sampling: even

_image_set_b_stimulus: &image_set_b
  class: images
  params:
    image_set: //allen/programs/braintv/workgroups/nc-ophys/visual_behavior/image_dictionaries/Natural_Images_Lum_Matched_set_ophys_3_2017.07.14.pkl
    sampling: even

_image_set_c_stimulus: &image_set_c
  class: images
  params:
    image_set: //allen/programs/braintv/workgroups/nc-ophys/visual_behavior/image_dictionaries/Natural_Images_Lum_Matched_set_ophys_6_2017.07.14.pkl
    sampling: even

_image_set_d_stimulus: &image_set_d
  class: images
  params:
    image_set: //allen/programs/braintv/workgroups/nc-ophys/visual_behavior/image_dictionaries/Natural_Images_Lum_Matched_set_ophys_5_2017.07.14.pkl
    sampling: even

_fingerprint_movie: &fingerprint_movie
  name: fingerprint
  params:
    movie_path: //allen/programs/braintv/workgroups/neuralcoding/Saskia/Visual Stimuli 151207/Movie_TOE1.npy
    frame_length: 0.03333333333333333
    size: [1920, 1080]
    runs: 10

_flash_parameters: &flash_parameters
  task_id: DoC

  catch_frequency: 0.25
  failure_repeats: 5

  # rewards (mL)
  reward_volume: 0.007
  volume_limit: 5.0

  # auto rewards
  auto_reward_vol: 0.005
  warm_up_trials: 5
  auto_reward_delay: 0.150
  free_reward_trials: 10000

  # trial timing
  min_no_lick_time: 0.0
  timeout_duration: 0.3
  pre_change_time: 0.0
  stimulus_window: 6.0
  max_task_duration_min: 60.0
  start_stop_padding: 20.0
  periodic_flash: [0.25, 0.5]
  response_window: [0.15, 0.75]
  end_after_response: True
  end_after_response_sec: 3.5

  # timing of changes
  change_time_dist: geometric
  change_time_scale: 0.3
  change_flashes_min: 4 # inclusive
  change_flashes_max: 12 # exclusive

_no_flash_parameters: &no_flash_parameters
  <<: *flash_parameters
  periodic_flash: null
  response_window: [0.15, 1.0]
  reward_volume: 0.010
  free_reward_trials: 10
  pre_change_time: 2.25

  # timing of changes
  change_time_dist: exponential
  change_time_scale: 2.0
  change_flashes_min: null
  change_flashes_max: null

_image_set_a_parameters: &image_set_a_parameters
  <<: *flash_parameters
  stimulus: *image_set_a
  catch_frequency: null

_image_set_b_parameters: &image_set_b_parameters
  <<: *flash_parameters
  stimulus: *image_set_b
  catch_frequency: null

_image_set_c_parameters: &image_set_c_parameters
  <<: *flash_parameters
  stimulus: *image_set_c
  catch_frequency: null

_image_set_d_parameters: &image_set_d_parameters
  <<: *flash_parameters
  stimulus: *image_set_d
  catch_frequency: null

_replay_a_parameters: &replay_a_parameters
  <<: *flash_parameters
  stimulus: *image_set_a
  catch_frequency: null
  mapping:
    flash_path: //allen/programs/braintv/workgroups/nc-ophys/1022/replay-stim/flash_250ms.stim
    gabor_path: //allen/programs/braintv/workgroups/nc-ophys/1022/replay-stim/gabor_20_deg_250ms.stim
  output_dir: C:/ProgramData/camstim/output

_replay_b_parameters: &replay_b_parameters
  <<: *flash_parameters
  stimulus: *image_set_b
  catch_frequency: null
  mapping:
    flash_path: //allen/programs/braintv/workgroups/nc-ophys/1022/replay-stim/flash_250ms.stim
    gabor_path: //allen/programs/braintv/workgroups/nc-ophys/1022/replay-stim/gabor_20_deg_250ms.stim
  output_dir: C:/ProgramData/camstim/output

### mtrain definitions
name: Test_Script_7_v0.0.3

transitions:
  - trigger: manual
    source: OPHYS_7_receptive_field_mapping_0
    dest: OPHYS_7_receptive_field_mapping_0

stages:
  OPHYS_7_receptive_field_mapping_0:
    script: *movie_clips_script
    script_md5: *movie_clips_script_md5
    parameters:
      stage: OPHYS_7_receptive_field_mapping
  c
    script: *movie_clips_script
    script_md5: *movie_clips_script_md5
    parameters:
      stage: OPHYS_7_receptive_field_mapping
