_passive_training_cluster_script: &passive_training_cluster_script http://stash.corp.alleninstitute.org/users/jeromel/repos/openscope-glo-stim/raw/pilot-scripts-allen/both-cohorts-habituation-drifting.py?at=b6886c086569527123c8cee48c921336c876c7ca
_passive_training_cluster_script_md5: &passive_training_cluster_script_md5 5f2ace77f11b7cb851b4057a826da638

_passive_prod_ephys_script: &passive_prod_ephys_script http://stash.corp.alleninstitute.org/users/jeromel/repos/openscope-glo-stim/raw/pilot-scripts-allen/both-cohorts-day-11-ephysrecording-120min-drifting.py?at=fcfc2065509ea1effeb8731835b5baf67be11a68
_passive_prod_ephys_script_md5: &passive_prod_ephys_script_md5 b3e0f721c4eafc3d4130ba53bcaa2007

_optotagging_script: &optotagging_script http://stash.corp.alleninstitute.org/users/jeromel/repos/openscope-glo-stim/raw/pilot-scripts-allen/opto-tagging-only.py?at=fcfc2065509ea1effeb8731835b5baf67be11a68
_optotagging_script_md5: &optotagging_script_md5 731b1dc38fc7e46e2d01c5710e252795

### mtrain definitions
name: Openscope_GlobalLocalOdd_Cohort2_v1

transitions:
  - trigger: progress
    source: PASSIVE_CLUSTER_HAB_10MIN_DAY6
    dest: PASSIVE_CLUSTER_HAB_20MIN_DAY7
    conditions: one_complete

  - trigger: progress
    source: PASSIVE_CLUSTER_HAB_20MIN_DAY7
    dest: PASSIVE_CLUSTER_HAB_30MIN_DAY8
    conditions: one_complete

  - trigger: progress
    source: PASSIVE_CLUSTER_HAB_30MIN_DAY8
    dest: PASSIVE_CLUSTER_HAB_40MIN_DAY9
    conditions: one_complete

  - trigger: progress
    source: PASSIVE_CLUSTER_HAB_40MIN_DAY9
    dest: PASSIVE_CLUSTER_HAB_50MIN_DAY10
    conditions: one_complete
  
  - trigger: manual
    source: PASSIVE_CLUSTER_HAB_50MIN_DAY10
    dest: PASSIVE_EPHYS_HAB_60MIN_DAY1_2

  - trigger: manual
    source: PASSIVE_EPHYS_HAB_60MIN_DAY1_2
    dest: PASSIVE_EPHYS_HAB_90MIN_DAY3_4

  - trigger: manual
    source: PASSIVE_EPHYS_HAB_90MIN_DAY3_4
    dest: PASSIVE_EPHYS_HAB_120MIN_DAY5

  - trigger: manual
    source: PASSIVE_EPHYS_HAB_120MIN_DAY5
    dest: PASSIVE_EPHYS_PROD_120MIN_DAY1

  - trigger: manual
    source: PASSIVE_EPHYS_PROD_120MIN_DAY1
    dest: OPTOTAGGING_ONLY

stages:
  PASSIVE_CLUSTER_HAB_10MIN_DAY6:
    script: *passive_training_cluster_script
    script_md5: *passive_training_cluster_script_md5
    parameters:
      stage: PASSIVE_CLUSTER_HAB_10MIN_DAY6
      habituation_time_min: 9.6
      cohort: 2
      stimulus_drift_rate: 0.0

  PASSIVE_CLUSTER_HAB_20MIN_DAY7:
    script: *passive_training_cluster_script
    script_md5: *passive_training_cluster_script_md5
    parameters:
      stage: PASSIVE_CLUSTER_HAB_20MIN_DAY7
      habituation_time_min: 19.4
      cohort: 2
      stimulus_drift_rate: 0.0

  PASSIVE_CLUSTER_HAB_30MIN_DAY8:
    script: *passive_training_cluster_script
    script_md5: *passive_training_cluster_script_md5
    parameters:
      stage: PASSIVE_CLUSTER_HAB_30MIN_DAY8
      habituation_time_min: 29.0
      cohort: 2
      stimulus_drift_rate: 0.0

  PASSIVE_CLUSTER_HAB_40MIN_DAY9:
    script: *passive_training_cluster_script
    script_md5: *passive_training_cluster_script_md5
    
    parameters:
      stage: PASSIVE_CLUSTER_HAB_40MIN_DAY9
      habituation_time_min:  38.8
      cohort: 2
      stimulus_drift_rate: 0.0

  PASSIVE_CLUSTER_HAB_50MIN_DAY10:
    script: *passive_training_cluster_script
    script_md5: *passive_training_cluster_script_md5

    parameters:
      stage: PASSIVE_CLUSTER_HAB_50MIN_DAY10
      habituation_time_min: 48.6
      cohort: 2
      stimulus_drift_rate: 0.0

  PASSIVE_EPHYS_HAB_60MIN_DAY1_2:
    script: *passive_training_cluster_script
    script_md5: *passive_training_cluster_script_md5

    parameters:
      stage: PASSIVE_EPHYS_HAB_60MIN_DAY1_2
      habituation_time_min: 58.4
      cohort: 2
      stimulus_drift_rate: 0.0

  PASSIVE_EPHYS_HAB_90MIN_DAY3_4:
    script: *passive_training_cluster_script
    script_md5: *passive_training_cluster_script_md5

    parameters:
      stage: PASSIVE_EPHYS_HAB_90MIN_DAY3_4
      habituation_time_min: 88.0
      cohort: 2
      stimulus_drift_rate: 0.0
      
  PASSIVE_EPHYS_HAB_120MIN_DAY5:
    script: *passive_training_cluster_script
    script_md5: *passive_training_cluster_script_md5

    parameters:
      stage: PASSIVE_EPHYS_HAB_120MIN_DAY5
      habituation_time_min: 117.4
      cohort: 2
      stimulus_drift_rate: 0.0

  PASSIVE_EPHYS_PROD_120MIN_DAY1:
    script: *passive_prod_ephys_script
    script_md5: *passive_prod_ephys_script_md5

    parameters:
      stage: PASSIVE_EPHYS_PROD_120MIN_DAY1
      cohort: 2
      stimulus_drift_rate: 0.0

      # optotagging      
      disable_opto: False

      opto_params: 
        operation_mode: "experiment"

  OPTOTAGGING_ONLY:
    script: *optotagging_script
    script_md5: *optotagging_script_md5
    parameters:
      stage: OPTOTAGGING_ONLY

      # optotagging      
      disable_opto: False

      opto_params: 
        operation_mode: "experiment"