_resource_id: &resource_id bcd1d5d18f28dbc7df17b0eabfa2c2759de52d1c

_gratings_stimulus: &gratings_stimulus
  class: gratings
  params:
    sf: 0.04
    size: [200, 150]
    units: deg
    tex: sqr
  groups:
    group_0:
      Ori: [90]
      phase: [0.25]
    group_1:
      Ori: [180]
      phase: [0.25]

_parameters: &parameters
  abort_on_early_response: false,
  auto_reward_delay: 0.15
  auto_reward_vol: 0.005 
  catch_frequency: 0.0 
  change_flashes_max: null 
  change_flashes_min: null 
  periodic_flash: null 
  change_time_dist: exponential
  change_time_scale: 2.0
  pre_change_time: 2.25
  stimulus_window: 6.0
  end_after_response: true
  end_after_response_sec: 3.5
  failure_repeats: 0
  start_stop_padding: 1
  free_reward_trials: 10
  max_task_duration_min: 15.0
  min_no_lick_time: 0.0
  response_window: [0.0, 0.0]
  reward_volume: 0.0
  volume_limit: 5.0
  warm_up_trials: -1
  task_id: DoC
  timeout_duration: 0.3

### mtrain definitions
name: AssociativeLearning_MatchVB

transitions:
  # in case a transition is required by mtrain
  - trigger: manual
    source: STAGE_0
    dest: STAGE_1

stages:
  STAGE_0:
    script: *resource_id
    script_md5: *resource_id # v2 compatability?
    parameters:
      <<: *parameters
      stage: STAGE_0
      stimulus: *gratings_stimulus
  STAGE_1:
    script: *resource_id
    script_md5: *resource_id # v2 compatability?
    parameters:
      <<: *parameters
      stage: STAGE_1
      stimulus: *gratings_stimulus
