_script: &script 
  https://raw.githubusercontent.com/samgale/DynamicRoutingTask/aa7ddaabde7b9a3899375bab020c1b85b586e9f2/runTask.py
_script_md5: 7dccc7db86bbe1a3f1e71429e7ee28f0
_parameters: &parameters
  mtrain_translator: dynamic_routing
  task_script_commit_hash: aa7ddaabde7b9a3899375bab020c1b85b586e9f2
  task_control_commit_hash: aa7ddaabde7b9a3899375bab020c1b85b586e9f2
  GHTaskScriptParams:
    taskScript: 
      https://raw.githubusercontent.com/samgale/DynamicRoutingTask/aa7ddaabde7b9a3899375bab020c1b85b586e9f2/DynamicRouting1.py
    taskControl: 
      https://raw.githubusercontent.com/samgale/DynamicRoutingTask/aa7ddaabde7b9a3899375bab020c1b85b586e9f2/TaskControl.py
### mtrain definitions
name: DynamicRouting_noAR_v0.0.2
transitions:
- trigger: progress
  source: STAGE_5_ORI_AMN_MOVING_NOAR
  dest: STAGE_5_AMN_ORI_MOVING_NOAR
- trigger: progress
  source: STAGE_5_AMN_ORI_MOVING_NOAR
  dest: STAGE_5_ORI_AMN_MOVING_NOAR
stages:
  STAGE_5_ORI_AMN_MOVING_NOAR:
    script: *script
    script_md5: 7dccc7db86bbe1a3f1e71429e7ee28f0
    parameters:
      <<: *parameters
      stage: STAGE_5_ORI_AMN_MOVING_NOAR
      taskVersion: stage 5 ori AMN moving noAR
  STAGE_5_AMN_ORI_MOVING_NOAR:
    script: *script
    script_md5: 7dccc7db86bbe1a3f1e71429e7ee28f0
    parameters:
      <<: *parameters
      stage: STAGE_5_AMN_ORI_MOVING_NOAR
      taskVersion: stage 5 AMN ori moving noAR