_script_0: &script_0 http://stash.corp.alleninstitute.org/projects/VB/repos/visual_behavior_scripts/raw/testing/TenSessionClips_0.py?at=500697e44ba5b7237ed7afc7cec069746f50892a

_script_0_md5: &script_0_md5 5f042b8ab04d6106d86d3d4fdcee5dc3

_script_1: &script_1 http://stash.corp.alleninstitute.org/projects/VB/repos/visual_behavior_scripts/raw/testing/gratings.py?at=500697e44ba5b7237ed7afc7cec069746f50892a

_script_1_md5: &script_1_md5 b31e254922529583bfc4f219e7050dfd

### mtrain definitions
#based on VisualBehavior_Task1A_v1.0.3
name: omFISH_Ophys_test_v0.0.2

transitions:
  - trigger: manual
    source: STAGE_0
    dest: STAGE_1

stages:
  STAGE_0:
    script: *script_0
    script_md5: *script_0_md5
    parameters:
      stage: STAGE_0
  STAGE_1:
    script: *script_1
    script_md5: *script_1_md5
    parameters:
      stage: STAGE_1
