_script_0: &script_0 http://stash.corp.alleninstitute.org/projects/VB/repos/visual_behavior_scripts/raw/testing/TenSessionClips_0.py?at=c0595a7a64f1d01215ff9a94d5fdb676c301f93c

_script_0_md5: &script_0_md5 a6ffc6eb8a39c8c50f01a701fd597b98


### mtrain definitions
name: V1omFISH_gamma_v1.0.0

transitions:
  - trigger: manual
    source: 40hz
    dest: 40hz_random

  - trigger: manual
    source: 40hz_random
    dest: square_stim

  - trigger: manual
    source: square_stim
    dest: 8hz

stages:
  40hz:
    script: *script_0
    script_md5: *script_0_md5
    parameters:
      stage: 40hz
  40hz_random:
    script: *script_0
    script_md5: *script_0_md5
    parameters:
      stage: 40hz_random
  square_stim:
    script: *script_0
    script_md5: *script_0_md5
    parameters:
      stage: square_stim
  8hz:
    script: *script_0
    script_md5: *script_0_md5
    parameters:
      stage: 8hz