_P3_script: &P3_script
    https://raw.githubusercontent.com/AllenNeuralDynamics/openscope-community-predictive-processing/512fd06e9634a7acfb01df31128ec61bad15ec8b/code/experiment-launcher/bonsai_experiment_launcher.py

_P3_script_md5: &P3_script_md5
    b501e3c16b747423e7ac3d92fdcff752

_bonsai_launcher_parameters: &bonsai_launcher_parameters
    repository_url: https://github.com/AllenNeuralDynamics/openscope-community-predictive-processing.git
    repository_commit_hash: 8518c21f4a85289ddb1bcaaa1f3f1fa884066fb2
    local_repository_path: C:/BonsaiDataPredictiveProcessingRepo
    bonsai_path: code/stimulus-control/src/Mindscope/generic_oddball.bonsai
    bonsai_exe_path: code/stimulus-control/bonsai/Bonsai.exe
    bonsai_setup_script: code/stimulus-control/bonsai/setup.cmd
    stimulus_table_duration: 00:01:00
    session_type: sensorimotor_no_oddball
    Photodiode_ExtentX: 8
    Photodiode_ExtentY: 8
    Photodiode_LocationX: 59
    Photodiode_LocationY: 28
    MotorCouplingCPD: 0.04
    WheelRadiusOverScreenRatio: 0.36 

### mtrain definitions
name: Openscope_P3_v23

transitions:

  - trigger: progress
    source: DAY_6
    dest: DAY_7
    conditions: one_complete

  - trigger: progress
    source: DAY_7
    dest: DAY_8
    conditions: one_complete

  - trigger: progress
    source: DAY_8
    dest: DAY_9
    conditions: one_complete

  - trigger: progress
    source: DAY_9
    dest: DAY_10
    conditions: one_complete

  - trigger: manual
    source: DAY_10
    dest: TRAIN_FULL_DAY1_5

  - trigger: manual
    source: TRAIN_FULL_DAY1_5
    dest: EPHYS_SESSION1_PROD_P3_SENSORYMOTOR

  - trigger: manual
    source: EPHYS_SESSION1_PROD_P3_SENSORYMOTOR
    dest: EPHYS_SESSION2_PROD_P3_STANDARD

  - trigger: manual
    source: EPHYS_SESSION2_PROD_P3_STANDARD
    dest: EPHYS_SESSION3_PROD_P3_SEQUENCE

  - trigger: manual
    source: EPHYS_SESSION3_PROD_P3_SEQUENCE
    dest: EPHYS_SESSION4_PROD_P3_DURATION

  - trigger: manual
    source: EPHYS_SESSION4_PROD_P3_DURATION
    dest: TEST_P3

stages:
    DAY_6:
        script: *P3_script
        script_md5: *P3_script_md5
        parameters:
            stage: DAY_6
            <<: *bonsai_launcher_parameters
            stimulus_table_duration: 00:08:00


    DAY_7:
        script: *P3_script
        script_md5: *P3_script_md5
        parameters:
            stage: DAY_7
            <<: *bonsai_launcher_parameters
            stimulus_table_duration: 00:18:00

    DAY_8:
        script: *P3_script
        script_md5: *P3_script_md5
        parameters:
            stage: DAY_8
            <<: *bonsai_launcher_parameters
            stimulus_table_duration: 00:28:00

    DAY_9:
        script: *P3_script
        script_md5: *P3_script_md5
        parameters:
            stage: DAY_9
            <<: *bonsai_launcher_parameters
            stimulus_table_duration: 00:38:00

    DAY_10:
        script: *P3_script
        script_md5: *P3_script_md5
        parameters:
            stage: DAY_10
            <<: *bonsai_launcher_parameters
            stimulus_table_duration: 00:48:00
            
    TRAIN_FULL_DAY1_5:
        script: *P3_script
        script_md5: *P3_script_md5
        parameters:
            stage: TRAIN_FULL_DAY1_5
            <<: *bonsai_launcher_parameters
            stimulus_table_duration: 02:00:00

    EPHYS_SESSION1_PROD_P3_SENSORYMOTOR:
        script: *P3_script
        script_md5: *P3_script_md5
        parameters:
            stage: EPHYS_SESSION1_PROD_P3_SENSORYMOTOR            
            <<: *bonsai_launcher_parameters
            stimulus_table_duration: 02:00:00
            session_type: sensorimotor_mismatch

    EPHYS_SESSION2_PROD_P3_STANDARD:
        script: *P3_script
        script_md5: *P3_script_md5
        parameters:
            stage: EPHYS_SESSION2_PROD_P3_STANDARD
            <<: *bonsai_launcher_parameters
            stimulus_table_duration: 02:00:00
            session_type: visual_mismatch

    EPHYS_SESSION3_PROD_P3_SEQUENCE:
        script: *P3_script
        script_md5: *P3_script_md5
        parameters:
            stage: EPHYS_SESSION3_PROD_P3_SEQUENCE
            <<: *bonsai_launcher_parameters
            stimulus_table_duration: 02:00:00
            session_type: sequence_mismatch

    EPHYS_SESSION4_PROD_P3_DURATION:
        script: *P3_script
        script_md5: *P3_script_md5
        parameters:
            stage: EPHYS_SESSION4_PROD_P3_DURATION
            <<: *bonsai_launcher_parameters
            stimulus_table_duration: 02:00:00
            session_type: duration_mismatch

    TEST_P3:
        script: *P3_script
        script_md5: *P3_script_md5
        parameters:
            stage: TEST_P3
            <<: *bonsai_launcher_parameters
            stimulus_table_duration: 00:10:00
