_passive_training_cluster_script: &passive_training_cluster_script http://stash.corp.alleninstitute.org/users/jeromel/repos/openscope-glo-stim/raw/production-scripts/habituation-FINAL.py?at=1f215487e0a5a860764b1782692690e40e6eb4e9
_passive_training_cluster_script_md5: &passive_training_cluster_script_md5 1517bd9d13c7c279b1b66cde0f7b3926

_passive_prod_ephys_script: &passive_prod_ephys_script http://stash.corp.alleninstitute.org/users/jeromel/repos/openscope-glo-stim/raw/production-scripts/ephysrecording-FINAL.py?at=1f215487e0a5a860764b1782692690e40e6eb4e9
_passive_prod_ephys_script_md5: &passive_prod_ephys_script_md5 4aa2c4f99ef9079cd2f7d65c2c6baae1

_optotagging_script: &optotagging_script http://stash.corp.alleninstitute.org/users/jeromel/repos/openscope-glo-stim/raw/pilot-scripts-allen/opto-tagging-only.py?at=f2edcca4c41f9a780ba564499809672748b53bf0
_optotagging_script_md5: &optotagging_script_md5 acab6e90112a1ec23adc25bea5406a5f

### mtrain definitions
name: Openscope_GlobalLocalOdd_Cohort2_v9

transitions:
  - trigger: progress
    source: PASSIVE_CLUSTER_HAB_10MIN_DAY6
    dest: PASSIVE_CLUSTER_HAB_20MIN_DAY7
    conditions: one_complete

  - trigger: progress
    source: PASSIVE_CLUSTER_HAB_20MIN_DAY7
    dest: PASSIVE_CLUSTER_HAB_30MIN_DAY8
    conditions: one_complete

  - trigger: progress
    source: PASSIVE_CLUSTER_HAB_30MIN_DAY8
    dest: PASSIVE_CLUSTER_HAB_40MIN_DAY9
    conditions: one_complete

  - trigger: progress
    source: PASSIVE_CLUSTER_HAB_40MIN_DAY9
    dest: PASSIVE_CLUSTER_HAB_50MIN_DAY10
    conditions: one_complete
  
  - trigger: manual
    source: PASSIVE_CLUSTER_HAB_50MIN_DAY10
    dest: PASSIVE_EPHYS_HAB_60MIN_DAY1_2

  - trigger: manual
    source: PASSIVE_EPHYS_HAB_60MIN_DAY1_2
    dest: PASSIVE_EPHYS_HAB_90MIN_DAY3_4

  - trigger: manual
    source: PASSIVE_EPHYS_HAB_90MIN_DAY3_4
    dest: PASSIVE_EPHYS_HAB_120MIN_DAY5

  - trigger: manual
    source: PASSIVE_EPHYS_HAB_120MIN_DAY5
    dest: PASSIVE_EPHYS_PROD_120MIN_DAY1

  - trigger: manual
    source: PASSIVE_EPHYS_PROD_120MIN_DAY1
    dest: PASSIVE_EPHYS_PROD_120MIN_DAY1_ALT

  - trigger: manual
    source: PASSIVE_EPHYS_PROD_120MIN_DAY1_ALT
    dest: OPTOTAGGING_ONLY

stages:
  PASSIVE_CLUSTER_HAB_10MIN_DAY6:
    script: *passive_training_cluster_script
    script_md5: *passive_training_cluster_script_md5
    parameters:
      stage: PASSIVE_CLUSTER_HAB_10MIN_DAY6
      habituation_time_min: 9.6
      cohort: 2
      stimulus_drift_rate: 4.0

  PASSIVE_CLUSTER_HAB_20MIN_DAY7:
    script: *passive_training_cluster_script
    script_md5: *passive_training_cluster_script_md5
    parameters:
      stage: PASSIVE_CLUSTER_HAB_20MIN_DAY7
      habituation_time_min: 19.4
      cohort: 2
      stimulus_drift_rate: 4.0

  PASSIVE_CLUSTER_HAB_30MIN_DAY8:
    script: *passive_training_cluster_script
    script_md5: *passive_training_cluster_script_md5
    parameters:
      stage: PASSIVE_CLUSTER_HAB_30MIN_DAY8
      habituation_time_min: 29.0
      cohort: 2
      stimulus_drift_rate: 4.0

  PASSIVE_CLUSTER_HAB_40MIN_DAY9:
    script: *passive_training_cluster_script
    script_md5: *passive_training_cluster_script_md5
    
    parameters:
      stage: PASSIVE_CLUSTER_HAB_40MIN_DAY9
      habituation_time_min:  38.8
      cohort: 2
      stimulus_drift_rate: 4.0

  PASSIVE_CLUSTER_HAB_50MIN_DAY10:
    script: *passive_training_cluster_script
    script_md5: *passive_training_cluster_script_md5

    parameters:
      stage: PASSIVE_CLUSTER_HAB_50MIN_DAY10
      habituation_time_min: 48.6
      cohort: 2
      stimulus_drift_rate: 4.0

  PASSIVE_EPHYS_HAB_60MIN_DAY1_2:
    script: *passive_training_cluster_script
    script_md5: *passive_training_cluster_script_md5

    parameters:
      stage: PASSIVE_EPHYS_HAB_60MIN_DAY1_2
      habituation_time_min: 58.4
      cohort: 2
      stimulus_drift_rate: 4.0

  PASSIVE_EPHYS_HAB_90MIN_DAY3_4:
    script: *passive_training_cluster_script
    script_md5: *passive_training_cluster_script_md5

    parameters:
      stage: PASSIVE_EPHYS_HAB_90MIN_DAY3_4
      habituation_time_min: 88.0
      cohort: 2
      stimulus_drift_rate: 4.0
      
  PASSIVE_EPHYS_HAB_120MIN_DAY5:
    script: *passive_training_cluster_script
    script_md5: *passive_training_cluster_script_md5

    parameters:
      stage: PASSIVE_EPHYS_HAB_120MIN_DAY5
      habituation_time_min: 117.4
      cohort: 2
      stimulus_drift_rate: 4.0

  PASSIVE_EPHYS_PROD_120MIN_DAY1:
    script: *passive_prod_ephys_script
    script_md5: *passive_prod_ephys_script_md5

    parameters:
      stage: PASSIVE_EPHYS_PROD_120MIN_DAY1
      cohort: 2
      stimulus_drift_rate: 4.0

      # optotagging      
      disable_opto: False

      opto_params: 
        operation_mode: "experiment"

  OPTOTAGGING_ONLY:
    script: *optotagging_script
    script_md5: *optotagging_script_md5
    parameters:
      stage: OPTOTAGGING_ONLY

      # optotagging      
      disable_opto: False

      opto_params: 
        operation_mode: "experiment"