_passive_training_cluster_script: &passive_training_cluster_script http://stash.corp.alleninstitute.org/users/jeromel/repos/illusionopenscope/raw/illusion_stimulus_pilot.py?at=405a3c84ebfd97c4fbe452f08198a56d1f2ecee6
_passive_training_cluster_script_md5: &passive_training_cluster_script_md5 76dc085a38d7322f7ef35a70df5245c0

_passive_training_ephys_script: &passive_training_ephys_script http://stash.corp.alleninstitute.org/users/jeromel/repos/illusionopenscope/raw/illusion_stimulus_habit.py?at=92e7913f5d453e59cd6aa6d275e522788b110693
_passive_training_ephys_script_md5: &passive_training_ephys_script_md5 381af3741e906398b29aec1b990187ed

_passive_prod_ephys_script: &passive_prod_ephys_script http://stash.corp.alleninstitute.org/users/jeromel/repos/illusionopenscope/raw/illusion_stimulus_fullpipe.py?at=ed5ef5abfa2b7fce79ee7c9f2097a8dd9d2d366d
_passive_prod_ephys_script_md5: &passive_prod_ephys_script_md5 130739f6fa85e56957883a27a6fc534b

_optotagging_script: &optotagging_script http://stash.corp.alleninstitute.org/users/jeromel/repos/illusionopenscope/raw/opto-tagging-only.py?at=f33c884c53c598557a9b93b16191633243049a91
_optotagging_script_md5: &optotagging_script_md5 fec596b7e8e1c2755d1696cedadd9990

### mtrain definitions
name: Openscope_Illusion_v4

transitions:
  - trigger: progress
    source: PASSIVE_CLUSTER_HAB_10MIN_DAY6
    dest: PASSIVE_CLUSTER_HAB_20MIN_DAY7
    conditions: one_complete

  - trigger: progress
    source: PASSIVE_CLUSTER_HAB_20MIN_DAY7
    dest: PASSIVE_CLUSTER_HAB_30MIN_DAY8
    conditions: one_complete

  - trigger: progress
    source: PASSIVE_CLUSTER_HAB_30MIN_DAY8
    dest: PASSIVE_CLUSTER_HAB_40MIN_DAY9
    conditions: one_complete

  - trigger: progress
    source: PASSIVE_CLUSTER_HAB_40MIN_DAY9
    dest: PASSIVE_CLUSTER_HAB_50MIN_DAY10
    conditions: one_complete
  
  - trigger: manual
    source: PASSIVE_CLUSTER_HAB_50MIN_DAY10
    dest: PASSIVE_EPHYS_HAB_60MIN_DAY1_2

  - trigger: manual
    source: PASSIVE_EPHYS_HAB_60MIN_DAY1_2
    dest: PASSIVE_EPHYS_HAB_90MIN_DAY3_4

  - trigger: manual
    source: PASSIVE_EPHYS_HAB_90MIN_DAY3_4
    dest: PASSIVE_EPHYS_HAB_120MIN_DAY5

  - trigger: manual
    source: PASSIVE_EPHYS_HAB_120MIN_DAY5
    dest: PASSIVE_EPHYS_PROD_120MIN_DAY1

  - trigger: manual
    source: PASSIVE_EPHYS_PROD_120MIN_DAY1
    dest: OPTOTAGGING_ONLY

stages:
  PASSIVE_CLUSTER_HAB_10MIN_DAY6:
    script: *passive_training_cluster_script
    script_md5: *passive_training_cluster_script_md5
    parameters:
      stage: PASSIVE_CLUSTER_HAB_10MIN_DAY6
      shared_repository_location: //allen/programs/mindscope/workgroups/openscope/2022-Illusion/Scripts/Production/illusionopenscope
      monitor_name: "Gamma1.Luminance50"

      # control number of repetition to make longer script
      Nrep: 2

  PASSIVE_CLUSTER_HAB_20MIN_DAY7:
    script: *passive_training_cluster_script
    script_md5: *passive_training_cluster_script_md5
    parameters:
      stage: PASSIVE_CLUSTER_HAB_20MIN_DAY7
      shared_repository_location: //allen/programs/mindscope/workgroups/openscope/2022-Illusion/Scripts/Production/illusionopenscope
      monitor_name: "Gamma1.Luminance50"

      # control number of repetition to make longer script
      Nrep: 5

  PASSIVE_CLUSTER_HAB_30MIN_DAY8:
    script: *passive_training_cluster_script
    script_md5: *passive_training_cluster_script_md5
    parameters:
      stage: PASSIVE_CLUSTER_HAB_30MIN_DAY8
      shared_repository_location: //allen/programs/mindscope/workgroups/openscope/2022-Illusion/Scripts/Production/illusionopenscope
      monitor_name: "Gamma1.Luminance50"

      # control number of repetition to make longer script
      Nrep: 8

  PASSIVE_CLUSTER_HAB_40MIN_DAY9:
    script: *passive_training_cluster_script
    script_md5: *passive_training_cluster_script_md5
    
    parameters:
      stage: PASSIVE_CLUSTER_HAB_40MIN_DAY9
      shared_repository_location: //allen/programs/mindscope/workgroups/openscope/2022-Illusion/Scripts/Production/illusionopenscope
      monitor_name: "Gamma1.Luminance50"

      # control number of repetition to make longer script
      Nrep: 10

  PASSIVE_CLUSTER_HAB_50MIN_DAY10:
    script: *passive_training_cluster_script
    script_md5: *passive_training_cluster_script_md5

    parameters:
      stage: PASSIVE_CLUSTER_HAB_50MIN_DAY10
      shared_repository_location: //allen/programs/mindscope/workgroups/openscope/2022-Illusion/Scripts/Production/illusionopenscope
      monitor_name: "Gamma1.Luminance50"

      # control number of repetition to make longer script
      Nrep: 14

  PASSIVE_EPHYS_HAB_60MIN_DAY1_2:
    script: *passive_training_ephys_script
    script_md5: *passive_training_ephys_script_md5

    parameters:
      stage: PASSIVE_EPHYS_HAB_60MIN_DAY1_2
      shared_repository_location: //allen/programs/mindscope/workgroups/openscope/2022-Illusion/Scripts/Production/illusionopenscope
      monitor_name: "Gamma1.Luminance50"

      # control number of repetition to make longer script
      DURFAC: 2

  PASSIVE_EPHYS_HAB_90MIN_DAY3_4:
    script: *passive_training_ephys_script
    script_md5: *passive_training_ephys_script_md5

    parameters:
      stage: PASSIVE_EPHYS_HAB_90MIN_DAY3_4
      shared_repository_location: //allen/programs/mindscope/workgroups/openscope/2022-Illusion/Scripts/Production/illusionopenscope
      monitor_name: "Gamma1.Luminance50"

      # control number of repetition to make longer script
      DURFAC: 3
      
  PASSIVE_EPHYS_HAB_120MIN_DAY5:
    script: *passive_prod_ephys_script
    script_md5: *passive_prod_ephys_script_md5

    parameters:
      stage: PASSIVE_EPHYS_HAB_120MIN_DAY5
      shared_repository_location: //allen/programs/mindscope/workgroups/openscope/2022-Illusion/Scripts/Production/illusionopenscope
      monitor_name: "Gamma1.Luminance50"

      # no optotagging
      disable_opto: True
      
  PASSIVE_EPHYS_PROD_120MIN_DAY1:
    script: *passive_prod_ephys_script
    script_md5: *passive_prod_ephys_script_md5

    parameters:
      stage: PASSIVE_EPHYS_PROD_120MIN_DAY1
      shared_repository_location: //allen/programs/mindscope/workgroups/openscope/2022-Illusion/Scripts/Production/illusionopenscope
      monitor_name: "Gamma1.Luminance50"

      # optotagging      
      disable_opto: False

      opto_params: 
        operation_mode: "experiment"

  OPTOTAGGING_ONLY:
    script: *optotagging_script
    script_md5: *optotagging_script_md5
    parameters:
      stage: OPTOTAGGING_ONLY

      # optotagging      
      disable_opto: False

      opto_params: 
        operation_mode: "experiment"