
_change_detection_script: &change_detection_script
    http://stash.corp.alleninstitute.org/projects/VB/repos/visual_behavior_scripts/raw/change_detection.py?at=22c5b52dcb8be244e1191590a95a72bf57f37a1a

_change_detection_script_md5: &change_detection_script_md5
    fa75e0fbd57a8af3019fc694b1f00517

_movie_clips_script: &movie_clips_script
    http://stash.corp.alleninstitute.org/projects/VB/repos/visual_behavior_scripts/raw/MovieClips.py?at=c0506e42f4cbb66721153c24b3e0c8e3825137e8

_movie_clips_script_md5: &movie_clips_script_md5
    922123fc5f902d7d364092bde3140f1f

_full_field_gratings_stimulus: &full_field_gratings
    class: grating
    params:
        sf: 0.04
        tex: sqr
        size: [200, 150,]
        units: deg
        phase: 0.25
    groups:
        group0:
            Ori: [0, 180]
        group1:
            Ori: [90, 270]

_image_set_a_stimulus: &image_set_a
    class: images
    params:
        # image_set: //allen/aibs/mpe/Software/stimulus_files/nimages_0_20170714.zip
        image_set: /allen/programs/braintv/workgroups/nc-ophys/Doug/Stimulus_Code/image_dictionaries/Natural_Images_Lum_Matched_set_training_2017.07.14.pkl
        sampling: even

_image_set_b_stimulus: &image_set_b
    class: images
    params:
        image_set: /allen/programs/braintv/workgroups/nc-ophys/Doug/Stimulus_Code/image_dictionaries/Natural_Images_Lum_Matched_set_3_2017.07.14.pkl
        sampling: even

_image_set_c_stimulus: &image_set_c
    class: images
    params:
        image_set: /allen/programs/braintv/workgroups/nc-ophys/Doug/Stimulus_Code/image_dictionaries/Natural_Images_Lum_Matched_set_6_2017.07.14.pkl
        sampling: even

_image_set_d_stimulus: &image_set_d
    class: images
    params:
        image_set: /allen/programs/braintv/workgroups/nc-ophys/Doug/Stimulus_Code/image_dictionaries/Natural_Images_Lum_Matched_set_5_2017.07.14.pkl
        sampling: even

_flash_parameters: &flash_parameters
    task_id: DoC

    catch_frequency: 0.25
    failure_repeats: 5

    # rewards (mL)
    reward_vol: 0.007
    volume_limit: 5.0

    # auto rewards
    auto_reward_vol: 0.005
    warm_up_trials: 5
    auto_reward_delay: 0.150
    free_reward_trials: 0

    # trial timing
    min_no_lick_time: 0.3
    pre_change_time: 2.25
    stimulus_window: 6.0
    max_task_duration_min: 60.0
    start_stop_padding: 10.0
    periodic_flash: [0.25, 0.5]
    response_window: [0.15,0.75]

    # timing of changes
    change_time_dist: exponential
    change_time_scale: 2.0

_no_flash_parameters: &no_flash_parameters
    <<: *flash_parameters
    periodic_flash: null
    response_window: [0.15,1.0]
    reward_vol: 0.010
    free_reward_trials: 10


_image_set_a_parameters: &image_set_a_parameters
    <<: *flash_parameters
    stimulus: *image_set_a
    catch_frequency: null

_image_set_c_parameters: &image_set_c_parameters
    <<: *flash_parameters
    stimulus: *image_set_c
    catch_frequency: null


### mtrain definitions

name: VisualBehavior_Task1A_v0.2.0

transitions:

  - trigger: progress
    source: 0_gratings_autorewards_15min
    dest: 1_gratings
    conditions: autorewards_complete

  - trigger: progress
    source: 1_gratings
    dest: 2_gratings_flashed
    conditions: [two_out_of_three_aint_bad, yesterday_was_good]

  - trigger: progress
    source: 2_gratings_flashed
    dest: 3_images_a_10uL_reward
    conditions: [two_out_of_three_aint_bad, yesterday_was_good]

  - trigger: progress
    source: 3_images_a_10uL_reward
    dest: 4_images_a_training
    conditions: three_complete

  - trigger: progress
    source: 4_images_a_training
    dest: 4_images_a_handoff_ready
    conditions: meets_engagement_criteria

  - trigger: progress
    source: 4_images_a_handoff_ready
    dest: 4_images_a_handoff_lapsed
    unless: meets_engagement_criteria

  - trigger: progress
    source: 4_images_a_handoff_lapsed
    dest: 4_images_a_handoff_ready
    conditions: meets_engagement_criteria

  - trigger: handoff
    source: 4_images_a_handoff_ready
    dest: 5_images_a_ophys
    conditions: meets_engagement_criteria

  - trigger: progress
    source: 5_images_a_ophys
    dest: 6_images_a_ophys_no_lickspout
    conditions: four_complete

  - trigger: progress
    source: 6_images_a_ophys_no_lickspout
    dest: 7_images_b_ophys
    conditions: one_complete

  - trigger: progress
    source: 7_images_b_ophys
    dest: 8_images_b_ophys_no_lickspout
    conditions: four_complete

  - trigger: progress
    source: 8_images_b_ophys_no_lickspout
    dest: 9_receptive_field_mapping
    conditions: one_complete

stages:

    0_gratings_autorewards_15min:
        script: *change_detection_script
        script_md5: *change_detection_script_md5
        parameters:
            <<: *no_flash_parameters
            stage: 0_gratings_autorewards_15min
            stimulus: *full_field_gratings

            # auto rewards
            warm_up_trials: -1 #infinite
            abort_on_early_response: False
            catch_frequency: 0.0

            response_window: [0.0, 0.0]
            min_no_lick_time: 0.0
            failure_repeats: 0

            # trial timing
            max_task_duration_min: 15.0


    1_gratings:
        script: *change_detection_script
        script_md5: *change_detection_script_md5
        parameters:
            <<: *no_flash_parameters
            stage: 1_gratings

            stimulus: *full_field_gratings


    2_gratings_flashed:
        script: *change_detection_script
        script_md5: *change_detection_script_md5
        parameters:
            <<: *flash_parameters
            stage: 2_gratings_flashed
            task_id: DoC

            stimulus: *full_field_gratings
            free_reward_trials: 10


    3_images_a_10uL_reward:
        script: *change_detection_script
        script_md5: *change_detection_script_md5
        parameters:
            <<: *image_set_a_parameters
            stage: 3_images_a_10uL_reward

            # rewards (mL)
            reward_vol: 0.01
            free_reward_trials: 10

    4_images_a_training:
        script: *change_detection_script
        script_md5: *change_detection_script_md5
        parameters:
            <<: *image_set_a_parameters
            stage: 4_images_a_training

    4_images_a_handoff_ready:
        script: *change_detection_script
        script_md5: *change_detection_script_md5
        parameters:
            <<: *image_set_a_parameters
            stage: 4_images_a_handoff_ready

    4_images_a_handoff_lapsed:
        script: *change_detection_script
        script_md5: *change_detection_script_md5
        parameters:
            <<: *image_set_a_parameters
            stage: 4_images_a_handoff_lapsed
            free_reward_trials: 10

    5_images_a_ophys:
        script: *change_detection_script
        script_md5: *change_detection_script_md5
        parameters:
            <<: *image_set_a_parameters
            stage: 5_images_a_ophys

    6_images_a_ophys_no_lickspout:
        script: *change_detection_script
        script_md5: *change_detection_script_md5
        parameters:
            <<: *image_set_a_parameters
            stage: 6_images_a_ophys_no_lickspout
            lick_spout: False

    7_images_b_ophys:
        script: *change_detection_script
        script_md5: *change_detection_script_md5
        parameters:
            <<: *image_set_c_parameters
            stage: 7_images_b_ophys

    8_images_b_ophys_no_lickspout:
        script: *change_detection_script
        script_md5: *change_detection_script_md5
        parameters:
            <<: *image_set_c_parameters
            stage: 8_images_b_ophys_no_lickspout
            lick_spout: False

    9_receptive_field_mapping:
        script: *movie_clips_script
        script_md5: *movie_clips_script_md5
        parameters:
            stage: 9_receptive_field_mapping
