_script: &script dynamic_routing.py
_script_md5: &script_md5 dynamic_routing.py
_parameters: &parameters
  mtrain_translator: "dynamic_routing"
  taskScript: //allen/programs/mindscope/workgroups/dynamicrouting/DynamicRoutingTask/DynamicRouting1.py
### mtrain definitions
name: DynamicRoutingAlternating_0_v0.0.0
transitions:
  - trigger: progress
    source: STAGE_5_ORI_AMN_MOVING_NOGO
    dest: STAGE_5_AMN_ORI_MOVING_NOGO
  - trigger: progress
    source: STAGE_5_AMN_ORI_MOVING_NOGO
    dest: STAGE_5_ORI_AMN_MOVING_NOGO
stages:
  STAGE_5_ORI_AMN_MOVING_NOGO:
    script: *script
    script_md5: *script_md5
    parameters:
      <<: *parameters
      stage: STAGE_5_ORI_AMN_MOVING_NOGO
      taskVersion: "stage 5 ori AMN moving nogo"
  STAGE_5_AMN_ORI_MOVING_NOGO:
    script: *script
    script_md5: *script_md5
    parameters:
      <<: *parameters
      stage: STAGE_5_AMN_ORI_MOVING_NOGO
      taskVersion: "stage 5 AMN ori moving nogo"
