static_full_field_gratings_flash_500ms:
    script:
        DoC_SummerPilot.py

    parameters:
        # major change: 'stimulus'
        stage: static_windowed_gratings_flash_500ms
        # stimulus
        stimulus: full_screen_square_wave
        delta_oris: [90]
        SF: 0.04
        catch_frequency: 0.25

        duration: 10

        # rewards
        rewardvol: 0.01 # in microliters
        task_mode: testing # 'testing' -> autoreward on change; 'training' -> must solicit reward
        volumelimit: 1.5

        # auto rewards
        warmup_trials: 5
        lick_detect_training_enabled: false # if mouse is not licking for multiple trials, deliver free rewards
        lick_detect_training_mode: single
        lick_detect_training_block_length: [8,12] # interval of consecutive trials without a lick to a free reward

        # timeout
        whitenoise_on_timeout: false
        blankscreen_on_timeout: false
        blankscreen_duration: 1
        timeout_duration: 0

        max_number_trial_repeats: 5

        # trial timing
        stim_duration: 0.25
        blank_duration_range: [0.5,0.5]
        initial_blank: 0
        delta_minimum: 0.75
        stimulus_distribution: 'exponential'
        delta_mean: 2
        trial_duration: 5
        response_window: [0.15,0.75]


        # misc
        frame_interval_plot: none