version: 2
jobs:

  test-27:
    docker:
      - image: circleci/python:2.7.13
    steps:
      - checkout
      - run:
          name: setup virtualenv
          command: virtualenv venv
      - run:
          name: install dependencies
          command: |
            . venv/bin/activate
            pip install -U pip pytest pyyaml requests
      - run:
          name: tox it up
          command: |
            . venv/bin/activate
            pytest

workflows:
  version: 2
  basic:
    jobs:
      - test-27
