1_AutoRewards:
    script:
        DoC_SummerPilot.py

    parameters:
        stage: 1_AutoRewards
        duration: 15

        # stimulus
        stimulus: full_screen_square_wave
        delta_oris: [90]
        SF: 0.04
        catch_frequency: 0

        # rewards
        rewardvol: 0.007 # in microliters
        task_mode: training # 'testing' -> autoreward on change; 'training' -> must solicit reward
        volumelimit: 1.5

        # auto rewards
        warmup_trials: 10

        # timeout
        ignore_false_alarms: True

        # trial timing
        stim_duration: 0.75
        blank_duration_range: [0.0,0.0]
        initial_blank: 0
        delta_minimum: 2.25
        stimulus_distribution: 'exponential'
        delta_mean: 2
        trial_duration: 8.25
        response_window: [0.15,1]

        # misc
        frame_interval_plot: none

static_full_field_gratings:
    script:
        DoC_SummerPilot.py

    parameters:
        stage: static_full_field_gratings

        # stimulus
        stimulus: full_screen_square_wave
        delta_oris: [90]
        SF: 0.04
        catch_frequency: 0.25

        # rewards
        rewardvol: 0.01 # in microliters
        task_mode: testing # 'testing' -> autoreward on change; 'training' -> must solicit reward
        volumelimit: 1.5

        # auto rewards
        warmup_trials: 5
        lick_detect_training_enabled: true # if mouse is not licking for multiple trials, deliver free rewards
        lick_detect_training_mode: single
        lick_detect_training_block_length: [8,12] # interval of consecutive trials without a lick to a free reward

        # timeout
        whitenoise_on_timeout: false
        blankscreen_on_timeout: false
        blankscreen_duration: 1
        timeout_duration: 0

        max_number_trial_repeats: 5

        # trial timing
        stim_duration: 0.75
        blank_duration_range: [0.0,0.0]
        initial_blank: 0
        delta_minimum: 2.25
        stimulus_distribution: 'exponential'
        delta_mean: 2
        trial_duration: 8.25
        response_window: [0.15,1]

        # misc
        frame_interval_plot: none


static_full_field_gratings_flash_500ms:
    script:
        DoC_SummerPilot.py

    parameters:
        # major change: 'stimulus'
        stage: static_windowed_gratings_flash_500ms
        # stimulus
        stimulus: full_screen_square_wave
        delta_oris: [90]
        SF: 0.04
        catch_frequency: 0.25

        # rewards
        rewardvol: 0.01 # in microliters
        task_mode: testing # 'testing' -> autoreward on change; 'training' -> must solicit reward
        volumelimit: 1.5

        # auto rewards
        warmup_trials: 5
        lick_detect_training_enabled: False # if mouse is not licking for multiple trials, deliver free rewards

        # timeout
        whitenoise_on_timeout: false
        blankscreen_on_timeout: false
        blankscreen_duration: 1
        timeout_duration: 0

        max_number_trial_repeats: 5

        # trial timing
        stim_duration: 0.25
        blank_duration_range: [0.5,0.5]
        initial_blank: 0
        delta_minimum: 2.25
        stimulus_distribution: 'exponential'
        delta_mean: 2
        trial_duration: 8.25
        response_window: [0.15,0.75]


        # misc
        frame_interval_plot: none

natural_images:
    script:
        DoC_SummerPilot.py

    parameters:
        task: DoC_NaturalImages_CAMMatched_n=8
        stage: natural_images
        # stimulus
        stimulus: Natural_Images_Lum_Matched_set_training_2017.07.14.pkl
        image_category_sampling_mode: even_sampling
        stimulus_size: [1174,918]
        stimulus_units: pix
        pos: [0,0]
        catch_frequency: 0.125 # 8 images -> 1/8 catch trials.

        # rewards
        rewardvol: 0.01 # in microliters
        task_mode: testing # 'testing' -> autoreward on change; 'training' -> must solicit reward
        volumelimit: 1.5

        # auto rewards
        warmup_trials: 5
        lick_detect_training_enabled: False # if mouse is not licking for multiple trials, deliver free rewards

        # timeout
        whitenoise_on_timeout: false
        blankscreen_on_timeout: false
        blankscreen_duration: 1
        timeout_duration: 0

        max_number_trial_repeats: 5

        # trial timing
        stim_duration: 0.25
        blank_duration_range: [0.5,0.5]
        initial_blank: 0
        delta_minimum: 2.25
        stimulus_distribution: 'exponential'
        delta_mean: 2
        trial_duration: 8.25
        response_window: [0.15,0.75]

        # misc
        frame_interval_plot: none

natural_images_drop_reward:
    script:
        DoC_SummerPilot.py

    parameters:
        task: DoC_NaturalImages_CAMMatched_n=8
        stage: natural_images_drop_reward
        # stimulus
        stimulus: Natural_Images_Lum_Matched_set_training_2017.07.14.pkl
        image_category_sampling_mode: even_sampling
        stimulus_size: [1174,918]
        stimulus_units: pix
        pos: [0,0]
        catch_frequency: 0.125 # 8 images -> 1/8 catch trials.

        # rewards
        rewardvol: 0.007 # in microliters
        task_mode: testing # 'testing' -> autoreward on change; 'training' -> must solicit reward
        volumelimit: 1.5

        # auto rewards
        warmup_trials: 5
        lick_detect_training_enabled: False # if mouse is not licking for multiple trials, deliver free rewards

        # timeout
        whitenoise_on_timeout: false
        blankscreen_on_timeout: false
        blankscreen_duration: 1
        timeout_duration: 0

        max_number_trial_repeats: 5

        # trial timing
        stim_duration: 0.25
        blank_duration_range: [0.5,0.5]
        initial_blank: 0
        delta_minimum: 2.25
        stimulus_distribution: 'exponential'
        delta_mean: 2
        trial_duration: 8.25
        response_window: [0.15,0.75]

        # misc
        frame_interval_plot: none


omitted_flashes:
    script:
        DoC_SummerPilot.py

    parameters:
        task: DoC_NaturalImages_CAMMatched_n=8
        stage: omitted_flashes
        # stimulus
        stimulus: Natural_Images_Lum_Matched_set_training_2017.07.14.pkl
        image_category_sampling_mode: even_sampling
        stimulus_size: [1174,918]
        stimulus_units: pix
        pos: [0,0]
        catch_frequency: 0.125 # 8 images -> 1/8 catch trials.

        # rewards
        rewardvol: 0.007 # in microliters
        task_mode: testing # 'testing' -> autoreward on change; 'training' -> must solicit reward
        volumelimit: 1.5

        # auto rewards
        warmup_trials: 5
        lick_detect_training_enabled: False # if mouse is not licking for multiple trials, deliver free rewards

        # timeout
        whitenoise_on_timeout: false
        blankscreen_on_timeout: false
        blankscreen_duration: 1
        timeout_duration: 0

        max_number_trial_repeats: 5

        # trial timing
        stim_duration: 0.25
        blank_duration_range: [0.5,0.5]
        initial_blank: 0
        delta_minimum: 2.25
        stimulus_distribution: 'exponential'
        delta_mean: 2
        trial_duration: 8.25
        response_window: [0.15,0.75]

        # misc
        frame_interval_plot: none
        
        # omitted flashes
        omitted_flash_fraction: 0.05
